// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: agent/proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_RegisterDevice_FullMethodName      = "/agent.AgentService/RegisterDevice"
	AgentService_VerifyDevice_FullMethodName        = "/agent.AgentService/VerifyDevice"
	AgentService_ReportHealth_FullMethodName        = "/agent.AgentService/ReportHealth"
	AgentService_GetConfiguration_FullMethodName    = "/agent.AgentService/GetConfiguration"
	AgentService_UpdateConfiguration_FullMethodName = "/agent.AgentService/UpdateConfiguration"
	AgentService_ListPlugins_FullMethodName         = "/agent.AgentService/ListPlugins"
	AgentService_InstallPlugin_FullMethodName       = "/agent.AgentService/InstallPlugin"
	AgentService_UninstallPlugin_FullMethodName     = "/agent.AgentService/UninstallPlugin"
	AgentService_ActivatePlugin_FullMethodName      = "/agent.AgentService/ActivatePlugin"
	AgentService_DeactivatePlugin_FullMethodName    = "/agent.AgentService/DeactivatePlugin"
	AgentService_GetPluginStatus_FullMethodName     = "/agent.AgentService/GetPluginStatus"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent Service - gRPC service for agent communication
type AgentServiceClient interface {
	// Device registration
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error)
	VerifyDevice(ctx context.Context, in *VerifyDeviceRequest, opts ...grpc.CallOption) (*VerifyDeviceResponse, error)
	// Health reporting
	ReportHealth(ctx context.Context, in *HealthReport, opts ...grpc.CallOption) (*HealthResponse, error)
	// Configuration management
	GetConfiguration(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	UpdateConfiguration(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	// Plugin management
	ListPlugins(ctx context.Context, in *PluginListRequest, opts ...grpc.CallOption) (*PluginListResponse, error)
	InstallPlugin(ctx context.Context, in *InstallPluginRequest, opts ...grpc.CallOption) (*InstallPluginResponse, error)
	UninstallPlugin(ctx context.Context, in *UninstallPluginRequest, opts ...grpc.CallOption) (*UninstallPluginResponse, error)
	ActivatePlugin(ctx context.Context, in *ActivatePluginRequest, opts ...grpc.CallOption) (*ActivatePluginResponse, error)
	DeactivatePlugin(ctx context.Context, in *DeactivatePluginRequest, opts ...grpc.CallOption) (*DeactivatePluginResponse, error)
	GetPluginStatus(ctx context.Context, in *PluginStatusRequest, opts ...grpc.CallOption) (*PluginStatusResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceResponse)
	err := c.cc.Invoke(ctx, AgentService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) VerifyDevice(ctx context.Context, in *VerifyDeviceRequest, opts ...grpc.CallOption) (*VerifyDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyDeviceResponse)
	err := c.cc.Invoke(ctx, AgentService_VerifyDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportHealth(ctx context.Context, in *HealthReport, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetConfiguration(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_GetConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateConfiguration(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_UpdateConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListPlugins(ctx context.Context, in *PluginListRequest, opts ...grpc.CallOption) (*PluginListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginListResponse)
	err := c.cc.Invoke(ctx, AgentService_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) InstallPlugin(ctx context.Context, in *InstallPluginRequest, opts ...grpc.CallOption) (*InstallPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallPluginResponse)
	err := c.cc.Invoke(ctx, AgentService_InstallPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UninstallPlugin(ctx context.Context, in *UninstallPluginRequest, opts ...grpc.CallOption) (*UninstallPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UninstallPluginResponse)
	err := c.cc.Invoke(ctx, AgentService_UninstallPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ActivatePlugin(ctx context.Context, in *ActivatePluginRequest, opts ...grpc.CallOption) (*ActivatePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivatePluginResponse)
	err := c.cc.Invoke(ctx, AgentService_ActivatePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeactivatePlugin(ctx context.Context, in *DeactivatePluginRequest, opts ...grpc.CallOption) (*DeactivatePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivatePluginResponse)
	err := c.cc.Invoke(ctx, AgentService_DeactivatePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetPluginStatus(ctx context.Context, in *PluginStatusRequest, opts ...grpc.CallOption) (*PluginStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_GetPluginStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// Agent Service - gRPC service for agent communication
type AgentServiceServer interface {
	// Device registration
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error)
	VerifyDevice(context.Context, *VerifyDeviceRequest) (*VerifyDeviceResponse, error)
	// Health reporting
	ReportHealth(context.Context, *HealthReport) (*HealthResponse, error)
	// Configuration management
	GetConfiguration(context.Context, *ConfigRequest) (*ConfigResponse, error)
	UpdateConfiguration(context.Context, *UpdateConfigRequest) (*ConfigResponse, error)
	// Plugin management
	ListPlugins(context.Context, *PluginListRequest) (*PluginListResponse, error)
	InstallPlugin(context.Context, *InstallPluginRequest) (*InstallPluginResponse, error)
	UninstallPlugin(context.Context, *UninstallPluginRequest) (*UninstallPluginResponse, error)
	ActivatePlugin(context.Context, *ActivatePluginRequest) (*ActivatePluginResponse, error)
	DeactivatePlugin(context.Context, *DeactivatePluginRequest) (*DeactivatePluginResponse, error)
	GetPluginStatus(context.Context, *PluginStatusRequest) (*PluginStatusResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedAgentServiceServer) VerifyDevice(context.Context, *VerifyDeviceRequest) (*VerifyDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyDevice not implemented")
}
func (UnimplementedAgentServiceServer) ReportHealth(context.Context, *HealthReport) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHealth not implemented")
}
func (UnimplementedAgentServiceServer) GetConfiguration(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedAgentServiceServer) UpdateConfiguration(context.Context, *UpdateConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfiguration not implemented")
}
func (UnimplementedAgentServiceServer) ListPlugins(context.Context, *PluginListRequest) (*PluginListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedAgentServiceServer) InstallPlugin(context.Context, *InstallPluginRequest) (*InstallPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallPlugin not implemented")
}
func (UnimplementedAgentServiceServer) UninstallPlugin(context.Context, *UninstallPluginRequest) (*UninstallPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UninstallPlugin not implemented")
}
func (UnimplementedAgentServiceServer) ActivatePlugin(context.Context, *ActivatePluginRequest) (*ActivatePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivatePlugin not implemented")
}
func (UnimplementedAgentServiceServer) DeactivatePlugin(context.Context, *DeactivatePluginRequest) (*DeactivatePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivatePlugin not implemented")
}
func (UnimplementedAgentServiceServer) GetPluginStatus(context.Context, *PluginStatusRequest) (*PluginStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginStatus not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_VerifyDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).VerifyDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_VerifyDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).VerifyDevice(ctx, req.(*VerifyDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportHealth(ctx, req.(*HealthReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetConfiguration(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpdateConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateConfiguration(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListPlugins(ctx, req.(*PluginListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_InstallPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).InstallPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_InstallPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).InstallPlugin(ctx, req.(*InstallPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UninstallPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UninstallPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UninstallPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UninstallPlugin(ctx, req.(*UninstallPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ActivatePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivatePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ActivatePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ActivatePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ActivatePlugin(ctx, req.(*ActivatePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeactivatePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivatePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeactivatePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeactivatePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeactivatePlugin(ctx, req.(*DeactivatePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetPluginStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetPluginStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetPluginStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetPluginStatus(ctx, req.(*PluginStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _AgentService_RegisterDevice_Handler,
		},
		{
			MethodName: "VerifyDevice",
			Handler:    _AgentService_VerifyDevice_Handler,
		},
		{
			MethodName: "ReportHealth",
			Handler:    _AgentService_ReportHealth_Handler,
		},
		{
			MethodName: "GetConfiguration",
			Handler:    _AgentService_GetConfiguration_Handler,
		},
		{
			MethodName: "UpdateConfiguration",
			Handler:    _AgentService_UpdateConfiguration_Handler,
		},
		{
			MethodName: "ListPlugins",
			Handler:    _AgentService_ListPlugins_Handler,
		},
		{
			MethodName: "InstallPlugin",
			Handler:    _AgentService_InstallPlugin_Handler,
		},
		{
			MethodName: "UninstallPlugin",
			Handler:    _AgentService_UninstallPlugin_Handler,
		},
		{
			MethodName: "ActivatePlugin",
			Handler:    _AgentService_ActivatePlugin_Handler,
		},
		{
			MethodName: "DeactivatePlugin",
			Handler:    _AgentService_DeactivatePlugin_Handler,
		},
		{
			MethodName: "GetPluginStatus",
			Handler:    _AgentService_GetPluginStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/proto/agent.proto",
}
