// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: services/geography/proto/geography.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Country messages
type GetCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountryRequest) Reset() {
	*x = GetCountryRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryRequest) ProtoMessage() {}

func (x *GetCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryRequest.ProtoReflect.Descriptor instead.
func (*GetCountryRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{0}
}

func (x *GetCountryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCountriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCountriesRequest) Reset() {
	*x = ListCountriesRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCountriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountriesRequest) ProtoMessage() {}

func (x *ListCountriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountriesRequest.ProtoReflect.Descriptor instead.
func (*ListCountriesRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{1}
}

type CreateCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCountryRequest) Reset() {
	*x = CreateCountryRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCountryRequest) ProtoMessage() {}

func (x *CreateCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCountryRequest.ProtoReflect.Descriptor instead.
func (*CreateCountryRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCountryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCountryRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdateCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Updates       map[string]string      `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCountryRequest) Reset() {
	*x = UpdateCountryRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCountryRequest) ProtoMessage() {}

func (x *UpdateCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCountryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCountryRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCountryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCountryRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

type DeleteCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCountryRequest) Reset() {
	*x = DeleteCountryRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCountryRequest) ProtoMessage() {}

func (x *DeleteCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCountryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCountryRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCountryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Country struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{5}
}

func (x *Country) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Country) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       *Country               `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryResponse) Reset() {
	*x = CountryResponse{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryResponse) ProtoMessage() {}

func (x *CountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryResponse.ProtoReflect.Descriptor instead.
func (*CountryResponse) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{6}
}

func (x *CountryResponse) GetCountry() *Country {
	if x != nil {
		return x.Country
	}
	return nil
}

type ListCountriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []*Country             `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCountriesResponse) Reset() {
	*x = ListCountriesResponse{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCountriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountriesResponse) ProtoMessage() {}

func (x *ListCountriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountriesResponse.ProtoReflect.Descriptor instead.
func (*ListCountriesResponse) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{7}
}

func (x *ListCountriesResponse) GetCountries() []*Country {
	if x != nil {
		return x.Countries
	}
	return nil
}

type DeleteCountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCountryResponse) Reset() {
	*x = DeleteCountryResponse{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCountryResponse) ProtoMessage() {}

func (x *DeleteCountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCountryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCountryResponse) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCountryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// City messages
type GetCityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCityRequest) Reset() {
	*x = GetCityRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCityRequest) ProtoMessage() {}

func (x *GetCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCityRequest.ProtoReflect.Descriptor instead.
func (*GetCityRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{9}
}

func (x *GetCityRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCitiesRequest) Reset() {
	*x = ListCitiesRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCitiesRequest) ProtoMessage() {}

func (x *ListCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCitiesRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{10}
}

type CreateCityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CountryId     int32                  `protobuf:"varint,2,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCityRequest) Reset() {
	*x = CreateCityRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCityRequest) ProtoMessage() {}

func (x *CreateCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCityRequest.ProtoReflect.Descriptor instead.
func (*CreateCityRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCityRequest) GetCountryId() int32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

type UpdateCityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Updates       map[string]string      `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCityRequest) Reset() {
	*x = UpdateCityRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCityRequest) ProtoMessage() {}

func (x *UpdateCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCityRequest.ProtoReflect.Descriptor instead.
func (*UpdateCityRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateCityRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCityRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

type DeleteCityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCityRequest) Reset() {
	*x = DeleteCityRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCityRequest) ProtoMessage() {}

func (x *DeleteCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCityRequest.ProtoReflect.Descriptor instead.
func (*DeleteCityRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCityRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type City struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CountryId     int32                  `protobuf:"varint,3,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *City) Reset() {
	*x = City{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{14}
}

func (x *City) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *City) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *City) GetCountryId() int32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

type CityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          *City                  `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityResponse) Reset() {
	*x = CityResponse{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityResponse) ProtoMessage() {}

func (x *CityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityResponse.ProtoReflect.Descriptor instead.
func (*CityResponse) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{15}
}

func (x *CityResponse) GetCity() *City {
	if x != nil {
		return x.City
	}
	return nil
}

type ListCitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cities        []*City                `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCitiesResponse) Reset() {
	*x = ListCitiesResponse{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCitiesResponse) ProtoMessage() {}

func (x *ListCitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCitiesResponse.ProtoReflect.Descriptor instead.
func (*ListCitiesResponse) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{16}
}

func (x *ListCitiesResponse) GetCities() []*City {
	if x != nil {
		return x.Cities
	}
	return nil
}

type DeleteCityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCityResponse) Reset() {
	*x = DeleteCityResponse{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCityResponse) ProtoMessage() {}

func (x *DeleteCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCityResponse.ProtoReflect.Descriptor instead.
func (*DeleteCityResponse) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteCityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Location messages
type GetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{18}
}

func (x *GetLocationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsRequest) Reset() {
	*x = ListLocationsRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsRequest) ProtoMessage() {}

func (x *ListLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsRequest.ProtoReflect.Descriptor instead.
func (*ListLocationsRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{19}
}

type CreateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocationRequest) Reset() {
	*x = CreateLocationRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocationRequest) ProtoMessage() {}

func (x *CreateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocationRequest.ProtoReflect.Descriptor instead.
func (*CreateLocationRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{20}
}

func (x *CreateLocationRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Updates       map[string]string      `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateLocationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateLocationRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

type DeleteLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLocationRequest) Reset() {
	*x = DeleteLocationRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLocationRequest) ProtoMessage() {}

func (x *DeleteLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLocationRequest.ProtoReflect.Descriptor instead.
func (*DeleteLocationRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteLocationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Location struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ZipCode        string                 `protobuf:"bytes,3,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	State          string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	BuildingNumber int32                  `protobuf:"varint,5,opt,name=building_number,json=buildingNumber,proto3" json:"building_number,omitempty"`
	RoomNumber     int32                  `protobuf:"varint,6,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Latitude       float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CountryId      int32                  `protobuf:"varint,9,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	CityId         int32                  `protobuf:"varint,10,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	LocationMap    string                 `protobuf:"bytes,11,opt,name=location_map,json=locationMap,proto3" json:"location_map,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{23}
}

func (x *Location) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Location) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Location) GetBuildingNumber() int32 {
	if x != nil {
		return x.BuildingNumber
	}
	return 0
}

func (x *Location) GetRoomNumber() int32 {
	if x != nil {
		return x.RoomNumber
	}
	return 0
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetCountryId() int32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *Location) GetCityId() int32 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *Location) GetLocationMap() string {
	if x != nil {
		return x.LocationMap
	}
	return ""
}

type LocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationResponse) Reset() {
	*x = LocationResponse{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationResponse) ProtoMessage() {}

func (x *LocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationResponse.ProtoReflect.Descriptor instead.
func (*LocationResponse) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{24}
}

func (x *LocationResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type ListLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsResponse) Reset() {
	*x = ListLocationsResponse{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsResponse) ProtoMessage() {}

func (x *ListLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsResponse.ProtoReflect.Descriptor instead.
func (*ListLocationsResponse) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{25}
}

func (x *ListLocationsResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

type DeleteLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLocationResponse) Reset() {
	*x = DeleteLocationResponse{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLocationResponse) ProtoMessage() {}

func (x *DeleteLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLocationResponse.ProtoReflect.Descriptor instead.
func (*DeleteLocationResponse) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Contact messages
type GetContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactRequest) Reset() {
	*x = GetContactRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactRequest) ProtoMessage() {}

func (x *GetContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactRequest.ProtoReflect.Descriptor instead.
func (*GetContactRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{27}
}

func (x *GetContactRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsRequest) Reset() {
	*x = ListContactsRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsRequest) ProtoMessage() {}

func (x *ListContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsRequest.ProtoReflect.Descriptor instead.
func (*ListContactsRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{28}
}

type CreateContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CountryId     int32                  `protobuf:"varint,2,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	MobileNumber  string                 `protobuf:"bytes,3,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Website       string                 `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContactRequest) Reset() {
	*x = CreateContactRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContactRequest) ProtoMessage() {}

func (x *CreateContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContactRequest.ProtoReflect.Descriptor instead.
func (*CreateContactRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{29}
}

func (x *CreateContactRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateContactRequest) GetCountryId() int32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *CreateContactRequest) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *CreateContactRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateContactRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *CreateContactRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Updates       map[string]string      `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContactRequest) Reset() {
	*x = UpdateContactRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContactRequest) ProtoMessage() {}

func (x *UpdateContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContactRequest.ProtoReflect.Descriptor instead.
func (*UpdateContactRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateContactRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateContactRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

type DeleteContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContactRequest) Reset() {
	*x = DeleteContactRequest{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactRequest) ProtoMessage() {}

func (x *DeleteContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactRequest.ProtoReflect.Descriptor instead.
func (*DeleteContactRequest) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteContactRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CountryId     int32                  `protobuf:"varint,3,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	MobileNumber  string                 `protobuf:"bytes,4,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Website       string                 `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{32}
}

func (x *Contact) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetCountryId() int32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *Contact) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *Contact) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Contact) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       *Contact               `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactResponse) Reset() {
	*x = ContactResponse{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactResponse) ProtoMessage() {}

func (x *ContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactResponse.ProtoReflect.Descriptor instead.
func (*ContactResponse) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{33}
}

func (x *ContactResponse) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type ListContactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      []*Contact             `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsResponse) Reset() {
	*x = ListContactsResponse{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsResponse) ProtoMessage() {}

func (x *ListContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsResponse.ProtoReflect.Descriptor instead.
func (*ListContactsResponse) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{34}
}

func (x *ListContactsResponse) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type DeleteContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContactResponse) Reset() {
	*x = DeleteContactResponse{}
	mi := &file_services_geography_proto_geography_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactResponse) ProtoMessage() {}

func (x *DeleteContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_geography_proto_geography_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactResponse.ProtoReflect.Descriptor instead.
func (*DeleteContactResponse) Descriptor() ([]byte, []int) {
	return file_services_geography_proto_geography_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteContactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_services_geography_proto_geography_proto protoreflect.FileDescriptor

const file_services_geography_proto_geography_proto_rawDesc = "" +
	"\n" +
	"(services/geography/proto/geography.proto\x12\tgeography\"#\n" +
	"\x11GetCountryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x16\n" +
	"\x14ListCountriesRequest\">\n" +
	"\x14CreateCountryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\xaa\x01\n" +
	"\x14UpdateCountryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12F\n" +
	"\aupdates\x18\x02 \x03(\v2,.geography.UpdateCountryRequest.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\x14DeleteCountryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"A\n" +
	"\aCountry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"?\n" +
	"\x0fCountryResponse\x12,\n" +
	"\acountry\x18\x01 \x01(\v2\x12.geography.CountryR\acountry\"I\n" +
	"\x15ListCountriesResponse\x120\n" +
	"\tcountries\x18\x01 \x03(\v2\x12.geography.CountryR\tcountries\"1\n" +
	"\x15DeleteCountryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\" \n" +
	"\x0eGetCityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x13\n" +
	"\x11ListCitiesRequest\"F\n" +
	"\x11CreateCityRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"country_id\x18\x02 \x01(\x05R\tcountryId\"\xa4\x01\n" +
	"\x11UpdateCityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12C\n" +
	"\aupdates\x18\x02 \x03(\v2).geography.UpdateCityRequest.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\x11DeleteCityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"I\n" +
	"\x04City\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"country_id\x18\x03 \x01(\x05R\tcountryId\"3\n" +
	"\fCityResponse\x12#\n" +
	"\x04city\x18\x01 \x01(\v2\x0f.geography.CityR\x04city\"=\n" +
	"\x12ListCitiesResponse\x12'\n" +
	"\x06cities\x18\x01 \x03(\v2\x0f.geography.CityR\x06cities\".\n" +
	"\x12DeleteCityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"$\n" +
	"\x12GetLocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x16\n" +
	"\x14ListLocationsRequest\"H\n" +
	"\x15CreateLocationRequest\x12/\n" +
	"\blocation\x18\x01 \x01(\v2\x13.geography.LocationR\blocation\"\xac\x01\n" +
	"\x15UpdateLocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12G\n" +
	"\aupdates\x18\x02 \x03(\v2-.geography.UpdateLocationRequest.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\x15DeleteLocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xbe\x02\n" +
	"\bLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bzip_code\x18\x03 \x01(\tR\azipCode\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12'\n" +
	"\x0fbuilding_number\x18\x05 \x01(\x05R\x0ebuildingNumber\x12\x1f\n" +
	"\vroom_number\x18\x06 \x01(\x05R\n" +
	"roomNumber\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"country_id\x18\t \x01(\x05R\tcountryId\x12\x17\n" +
	"\acity_id\x18\n" +
	" \x01(\x05R\x06cityId\x12!\n" +
	"\flocation_map\x18\v \x01(\tR\vlocationMap\"C\n" +
	"\x10LocationResponse\x12/\n" +
	"\blocation\x18\x01 \x01(\v2\x13.geography.LocationR\blocation\"J\n" +
	"\x15ListLocationsResponse\x121\n" +
	"\tlocations\x18\x01 \x03(\v2\x13.geography.LocationR\tlocations\"2\n" +
	"\x16DeleteLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11GetContactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x15\n" +
	"\x13ListContactsRequest\"\xc1\x01\n" +
	"\x14CreateContactRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"country_id\x18\x02 \x01(\x05R\tcountryId\x12#\n" +
	"\rmobile_number\x18\x03 \x01(\tR\fmobileNumber\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\awebsite\x18\x05 \x01(\tR\awebsite\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\"\xaa\x01\n" +
	"\x14UpdateContactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12F\n" +
	"\aupdates\x18\x02 \x03(\v2,.geography.UpdateContactRequest.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\x14DeleteContactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xc4\x01\n" +
	"\aContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"country_id\x18\x03 \x01(\x05R\tcountryId\x12#\n" +
	"\rmobile_number\x18\x04 \x01(\tR\fmobileNumber\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\awebsite\x18\x06 \x01(\tR\awebsite\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\"?\n" +
	"\x0fContactResponse\x12,\n" +
	"\acontact\x18\x01 \x01(\v2\x12.geography.ContactR\acontact\"F\n" +
	"\x14ListContactsResponse\x12.\n" +
	"\bcontacts\x18\x01 \x03(\v2\x12.geography.ContactR\bcontacts\"1\n" +
	"\x15DeleteContactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x9e\f\n" +
	"\x10GeographyService\x12F\n" +
	"\n" +
	"GetCountry\x12\x1c.geography.GetCountryRequest\x1a\x1a.geography.CountryResponse\x12R\n" +
	"\rListCountries\x12\x1f.geography.ListCountriesRequest\x1a .geography.ListCountriesResponse\x12L\n" +
	"\rCreateCountry\x12\x1f.geography.CreateCountryRequest\x1a\x1a.geography.CountryResponse\x12L\n" +
	"\rUpdateCountry\x12\x1f.geography.UpdateCountryRequest\x1a\x1a.geography.CountryResponse\x12R\n" +
	"\rDeleteCountry\x12\x1f.geography.DeleteCountryRequest\x1a .geography.DeleteCountryResponse\x12=\n" +
	"\aGetCity\x12\x19.geography.GetCityRequest\x1a\x17.geography.CityResponse\x12I\n" +
	"\n" +
	"ListCities\x12\x1c.geography.ListCitiesRequest\x1a\x1d.geography.ListCitiesResponse\x12C\n" +
	"\n" +
	"CreateCity\x12\x1c.geography.CreateCityRequest\x1a\x17.geography.CityResponse\x12C\n" +
	"\n" +
	"UpdateCity\x12\x1c.geography.UpdateCityRequest\x1a\x17.geography.CityResponse\x12I\n" +
	"\n" +
	"DeleteCity\x12\x1c.geography.DeleteCityRequest\x1a\x1d.geography.DeleteCityResponse\x12I\n" +
	"\vGetLocation\x12\x1d.geography.GetLocationRequest\x1a\x1b.geography.LocationResponse\x12R\n" +
	"\rListLocations\x12\x1f.geography.ListLocationsRequest\x1a .geography.ListLocationsResponse\x12O\n" +
	"\x0eCreateLocation\x12 .geography.CreateLocationRequest\x1a\x1b.geography.LocationResponse\x12O\n" +
	"\x0eUpdateLocation\x12 .geography.UpdateLocationRequest\x1a\x1b.geography.LocationResponse\x12U\n" +
	"\x0eDeleteLocation\x12 .geography.DeleteLocationRequest\x1a!.geography.DeleteLocationResponse\x12F\n" +
	"\n" +
	"GetContact\x12\x1c.geography.GetContactRequest\x1a\x1a.geography.ContactResponse\x12O\n" +
	"\fListContacts\x12\x1e.geography.ListContactsRequest\x1a\x1f.geography.ListContactsResponse\x12L\n" +
	"\rCreateContact\x12\x1f.geography.CreateContactRequest\x1a\x1a.geography.ContactResponse\x12L\n" +
	"\rUpdateContact\x12\x1f.geography.UpdateContactRequest\x1a\x1a.geography.ContactResponse\x12R\n" +
	"\rDeleteContact\x12\x1f.geography.DeleteContactRequest\x1a .geography.DeleteContactResponseB\"Z backend/services/geography/protob\x06proto3"

var (
	file_services_geography_proto_geography_proto_rawDescOnce sync.Once
	file_services_geography_proto_geography_proto_rawDescData []byte
)

func file_services_geography_proto_geography_proto_rawDescGZIP() []byte {
	file_services_geography_proto_geography_proto_rawDescOnce.Do(func() {
		file_services_geography_proto_geography_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_geography_proto_geography_proto_rawDesc), len(file_services_geography_proto_geography_proto_rawDesc)))
	})
	return file_services_geography_proto_geography_proto_rawDescData
}

var file_services_geography_proto_geography_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_services_geography_proto_geography_proto_goTypes = []any{
	(*GetCountryRequest)(nil),      // 0: geography.GetCountryRequest
	(*ListCountriesRequest)(nil),   // 1: geography.ListCountriesRequest
	(*CreateCountryRequest)(nil),   // 2: geography.CreateCountryRequest
	(*UpdateCountryRequest)(nil),   // 3: geography.UpdateCountryRequest
	(*DeleteCountryRequest)(nil),   // 4: geography.DeleteCountryRequest
	(*Country)(nil),                // 5: geography.Country
	(*CountryResponse)(nil),        // 6: geography.CountryResponse
	(*ListCountriesResponse)(nil),  // 7: geography.ListCountriesResponse
	(*DeleteCountryResponse)(nil),  // 8: geography.DeleteCountryResponse
	(*GetCityRequest)(nil),         // 9: geography.GetCityRequest
	(*ListCitiesRequest)(nil),      // 10: geography.ListCitiesRequest
	(*CreateCityRequest)(nil),      // 11: geography.CreateCityRequest
	(*UpdateCityRequest)(nil),      // 12: geography.UpdateCityRequest
	(*DeleteCityRequest)(nil),      // 13: geography.DeleteCityRequest
	(*City)(nil),                   // 14: geography.City
	(*CityResponse)(nil),           // 15: geography.CityResponse
	(*ListCitiesResponse)(nil),     // 16: geography.ListCitiesResponse
	(*DeleteCityResponse)(nil),     // 17: geography.DeleteCityResponse
	(*GetLocationRequest)(nil),     // 18: geography.GetLocationRequest
	(*ListLocationsRequest)(nil),   // 19: geography.ListLocationsRequest
	(*CreateLocationRequest)(nil),  // 20: geography.CreateLocationRequest
	(*UpdateLocationRequest)(nil),  // 21: geography.UpdateLocationRequest
	(*DeleteLocationRequest)(nil),  // 22: geography.DeleteLocationRequest
	(*Location)(nil),               // 23: geography.Location
	(*LocationResponse)(nil),       // 24: geography.LocationResponse
	(*ListLocationsResponse)(nil),  // 25: geography.ListLocationsResponse
	(*DeleteLocationResponse)(nil), // 26: geography.DeleteLocationResponse
	(*GetContactRequest)(nil),      // 27: geography.GetContactRequest
	(*ListContactsRequest)(nil),    // 28: geography.ListContactsRequest
	(*CreateContactRequest)(nil),   // 29: geography.CreateContactRequest
	(*UpdateContactRequest)(nil),   // 30: geography.UpdateContactRequest
	(*DeleteContactRequest)(nil),   // 31: geography.DeleteContactRequest
	(*Contact)(nil),                // 32: geography.Contact
	(*ContactResponse)(nil),        // 33: geography.ContactResponse
	(*ListContactsResponse)(nil),   // 34: geography.ListContactsResponse
	(*DeleteContactResponse)(nil),  // 35: geography.DeleteContactResponse
	nil,                            // 36: geography.UpdateCountryRequest.UpdatesEntry
	nil,                            // 37: geography.UpdateCityRequest.UpdatesEntry
	nil,                            // 38: geography.UpdateLocationRequest.UpdatesEntry
	nil,                            // 39: geography.UpdateContactRequest.UpdatesEntry
}
var file_services_geography_proto_geography_proto_depIdxs = []int32{
	36, // 0: geography.UpdateCountryRequest.updates:type_name -> geography.UpdateCountryRequest.UpdatesEntry
	5,  // 1: geography.CountryResponse.country:type_name -> geography.Country
	5,  // 2: geography.ListCountriesResponse.countries:type_name -> geography.Country
	37, // 3: geography.UpdateCityRequest.updates:type_name -> geography.UpdateCityRequest.UpdatesEntry
	14, // 4: geography.CityResponse.city:type_name -> geography.City
	14, // 5: geography.ListCitiesResponse.cities:type_name -> geography.City
	23, // 6: geography.CreateLocationRequest.location:type_name -> geography.Location
	38, // 7: geography.UpdateLocationRequest.updates:type_name -> geography.UpdateLocationRequest.UpdatesEntry
	23, // 8: geography.LocationResponse.location:type_name -> geography.Location
	23, // 9: geography.ListLocationsResponse.locations:type_name -> geography.Location
	39, // 10: geography.UpdateContactRequest.updates:type_name -> geography.UpdateContactRequest.UpdatesEntry
	32, // 11: geography.ContactResponse.contact:type_name -> geography.Contact
	32, // 12: geography.ListContactsResponse.contacts:type_name -> geography.Contact
	0,  // 13: geography.GeographyService.GetCountry:input_type -> geography.GetCountryRequest
	1,  // 14: geography.GeographyService.ListCountries:input_type -> geography.ListCountriesRequest
	2,  // 15: geography.GeographyService.CreateCountry:input_type -> geography.CreateCountryRequest
	3,  // 16: geography.GeographyService.UpdateCountry:input_type -> geography.UpdateCountryRequest
	4,  // 17: geography.GeographyService.DeleteCountry:input_type -> geography.DeleteCountryRequest
	9,  // 18: geography.GeographyService.GetCity:input_type -> geography.GetCityRequest
	10, // 19: geography.GeographyService.ListCities:input_type -> geography.ListCitiesRequest
	11, // 20: geography.GeographyService.CreateCity:input_type -> geography.CreateCityRequest
	12, // 21: geography.GeographyService.UpdateCity:input_type -> geography.UpdateCityRequest
	13, // 22: geography.GeographyService.DeleteCity:input_type -> geography.DeleteCityRequest
	18, // 23: geography.GeographyService.GetLocation:input_type -> geography.GetLocationRequest
	19, // 24: geography.GeographyService.ListLocations:input_type -> geography.ListLocationsRequest
	20, // 25: geography.GeographyService.CreateLocation:input_type -> geography.CreateLocationRequest
	21, // 26: geography.GeographyService.UpdateLocation:input_type -> geography.UpdateLocationRequest
	22, // 27: geography.GeographyService.DeleteLocation:input_type -> geography.DeleteLocationRequest
	27, // 28: geography.GeographyService.GetContact:input_type -> geography.GetContactRequest
	28, // 29: geography.GeographyService.ListContacts:input_type -> geography.ListContactsRequest
	29, // 30: geography.GeographyService.CreateContact:input_type -> geography.CreateContactRequest
	30, // 31: geography.GeographyService.UpdateContact:input_type -> geography.UpdateContactRequest
	31, // 32: geography.GeographyService.DeleteContact:input_type -> geography.DeleteContactRequest
	6,  // 33: geography.GeographyService.GetCountry:output_type -> geography.CountryResponse
	7,  // 34: geography.GeographyService.ListCountries:output_type -> geography.ListCountriesResponse
	6,  // 35: geography.GeographyService.CreateCountry:output_type -> geography.CountryResponse
	6,  // 36: geography.GeographyService.UpdateCountry:output_type -> geography.CountryResponse
	8,  // 37: geography.GeographyService.DeleteCountry:output_type -> geography.DeleteCountryResponse
	15, // 38: geography.GeographyService.GetCity:output_type -> geography.CityResponse
	16, // 39: geography.GeographyService.ListCities:output_type -> geography.ListCitiesResponse
	15, // 40: geography.GeographyService.CreateCity:output_type -> geography.CityResponse
	15, // 41: geography.GeographyService.UpdateCity:output_type -> geography.CityResponse
	17, // 42: geography.GeographyService.DeleteCity:output_type -> geography.DeleteCityResponse
	24, // 43: geography.GeographyService.GetLocation:output_type -> geography.LocationResponse
	25, // 44: geography.GeographyService.ListLocations:output_type -> geography.ListLocationsResponse
	24, // 45: geography.GeographyService.CreateLocation:output_type -> geography.LocationResponse
	24, // 46: geography.GeographyService.UpdateLocation:output_type -> geography.LocationResponse
	26, // 47: geography.GeographyService.DeleteLocation:output_type -> geography.DeleteLocationResponse
	33, // 48: geography.GeographyService.GetContact:output_type -> geography.ContactResponse
	34, // 49: geography.GeographyService.ListContacts:output_type -> geography.ListContactsResponse
	33, // 50: geography.GeographyService.CreateContact:output_type -> geography.ContactResponse
	33, // 51: geography.GeographyService.UpdateContact:output_type -> geography.ContactResponse
	35, // 52: geography.GeographyService.DeleteContact:output_type -> geography.DeleteContactResponse
	33, // [33:53] is the sub-list for method output_type
	13, // [13:33] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_services_geography_proto_geography_proto_init() }
func file_services_geography_proto_geography_proto_init() {
	if File_services_geography_proto_geography_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_geography_proto_geography_proto_rawDesc), len(file_services_geography_proto_geography_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_geography_proto_geography_proto_goTypes,
		DependencyIndexes: file_services_geography_proto_geography_proto_depIdxs,
		MessageInfos:      file_services_geography_proto_geography_proto_msgTypes,
	}.Build()
	File_services_geography_proto_geography_proto = out.File
	file_services_geography_proto_geography_proto_goTypes = nil
	file_services_geography_proto_geography_proto_depIdxs = nil
}
