// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: services/helpdesk/proto/helpdesk.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ticket Messages
type CreateTicketRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	HelpDeskTypeId int32                  `protobuf:"varint,3,opt,name=help_desk_type_id,json=helpDeskTypeId,proto3" json:"help_desk_type_id,omitempty"`
	PortalUserId   int32                  `protobuf:"varint,4,opt,name=portal_user_id,json=portalUserId,proto3" json:"portal_user_id,omitempty"`
	State          string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	ParentId       int32                  `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ProjectId      int32                  `protobuf:"varint,7,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTicketRequest) Reset() {
	*x = CreateTicketRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketRequest) ProtoMessage() {}

func (x *CreateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTicketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTicketRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTicketRequest) GetHelpDeskTypeId() int32 {
	if x != nil {
		return x.HelpDeskTypeId
	}
	return 0
}

func (x *CreateTicketRequest) GetPortalUserId() int32 {
	if x != nil {
		return x.PortalUserId
	}
	return 0
}

func (x *CreateTicketRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateTicketRequest) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateTicketRequest) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type GetTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int32                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{1}
}

func (x *GetTicketRequest) GetTicketId() int32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type UpdateTicketRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TicketId       int32                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	State          string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	HelpDeskTypeId int32                  `protobuf:"varint,5,opt,name=help_desk_type_id,json=helpDeskTypeId,proto3" json:"help_desk_type_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTicketRequest) Reset() {
	*x = UpdateTicketRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketRequest) ProtoMessage() {}

func (x *UpdateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTicketRequest) GetTicketId() int32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *UpdateTicketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTicketRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTicketRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UpdateTicketRequest) GetHelpDeskTypeId() int32 {
	if x != nil {
		return x.HelpDeskTypeId
	}
	return 0
}

type ListTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsRequest) Reset() {
	*x = ListTicketsRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsRequest) ProtoMessage() {}

func (x *ListTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsRequest.ProtoReflect.Descriptor instead.
func (*ListTicketsRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{3}
}

func (x *ListTicketsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTicketsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTicketsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListTicketsRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ListTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*TicketResponse      `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsResponse) Reset() {
	*x = ListTicketsResponse{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsResponse) ProtoMessage() {}

func (x *ListTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsResponse.ProtoReflect.Descriptor instead.
func (*ListTicketsResponse) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{4}
}

func (x *ListTicketsResponse) GetTickets() []*TicketResponse {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *ListTicketsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTicketsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTicketsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeleteTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int32                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTicketRequest) Reset() {
	*x = DeleteTicketRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTicketRequest) ProtoMessage() {}

func (x *DeleteTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTicketRequest.ProtoReflect.Descriptor instead.
func (*DeleteTicketRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTicketRequest) GetTicketId() int32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type TicketResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreateDate     string                 `protobuf:"bytes,3,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	HelpDeskTypeId int32                  `protobuf:"varint,4,opt,name=help_desk_type_id,json=helpDeskTypeId,proto3" json:"help_desk_type_id,omitempty"`
	PortalUserId   int32                  `protobuf:"varint,5,opt,name=portal_user_id,json=portalUserId,proto3" json:"portal_user_id,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	State          string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	ResolveDate    string                 `protobuf:"bytes,8,opt,name=resolve_date,json=resolveDate,proto3" json:"resolve_date,omitempty"`
	ParentId       int32                  `protobuf:"varint,9,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ProjectId      int32                  `protobuf:"varint,10,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TicketResponse) Reset() {
	*x = TicketResponse{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketResponse) ProtoMessage() {}

func (x *TicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketResponse.ProtoReflect.Descriptor instead.
func (*TicketResponse) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{6}
}

func (x *TicketResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TicketResponse) GetCreateDate() string {
	if x != nil {
		return x.CreateDate
	}
	return ""
}

func (x *TicketResponse) GetHelpDeskTypeId() int32 {
	if x != nil {
		return x.HelpDeskTypeId
	}
	return 0
}

func (x *TicketResponse) GetPortalUserId() int32 {
	if x != nil {
		return x.PortalUserId
	}
	return 0
}

func (x *TicketResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TicketResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TicketResponse) GetResolveDate() string {
	if x != nil {
		return x.ResolveDate
	}
	return ""
}

func (x *TicketResponse) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *TicketResponse) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

// Comment Messages
type AddCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int32                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{7}
}

func (x *AddCommentRequest) GetTicketId() int32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *AddCommentRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int32                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{8}
}

func (x *GetCommentsRequest) GetTicketId() int32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentResponse     `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{9}
}

func (x *GetCommentsResponse) GetComments() []*CommentResponse {
	if x != nil {
		return x.Comments
	}
	return nil
}

type CommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      int32                  `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{10}
}

func (x *CommentResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentResponse) GetTicketId() int32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *CommentResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Attachment Messages
type AddAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int32                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	DocumentType  string                 `protobuf:"bytes,4,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAttachmentRequest) Reset() {
	*x = AddAttachmentRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAttachmentRequest) ProtoMessage() {}

func (x *AddAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAttachmentRequest.ProtoReflect.Descriptor instead.
func (*AddAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{11}
}

func (x *AddAttachmentRequest) GetTicketId() int32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *AddAttachmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddAttachmentRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AddAttachmentRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

type GetAttachmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int32                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentsRequest) Reset() {
	*x = GetAttachmentsRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentsRequest) ProtoMessage() {}

func (x *GetAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*GetAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{12}
}

func (x *GetAttachmentsRequest) GetTicketId() int32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type GetAttachmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attachments   []*AttachmentResponse  `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentsResponse) Reset() {
	*x = GetAttachmentsResponse{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentsResponse) ProtoMessage() {}

func (x *GetAttachmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentsResponse.ProtoReflect.Descriptor instead.
func (*GetAttachmentsResponse) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{13}
}

func (x *GetAttachmentsResponse) GetAttachments() []*AttachmentResponse {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type AttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      int32                  `protobuf:"varint,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DocumentType  string                 `protobuf:"bytes,4,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentResponse) Reset() {
	*x = AttachmentResponse{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentResponse) ProtoMessage() {}

func (x *AttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentResponse.ProtoReflect.Descriptor instead.
func (*AttachmentResponse) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{14}
}

func (x *AttachmentResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttachmentResponse) GetTicketId() int32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *AttachmentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttachmentResponse) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *AttachmentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Assignment Messages
type AssignUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int32                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserRequest) Reset() {
	*x = AssignUserRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserRequest) ProtoMessage() {}

func (x *AssignUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserRequest.ProtoReflect.Descriptor instead.
func (*AssignUserRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{15}
}

func (x *AssignUserRequest) GetTicketId() int32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *AssignUserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AssignUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserResponse) Reset() {
	*x = AssignUserResponse{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserResponse) ProtoMessage() {}

func (x *AssignUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserResponse.ProtoReflect.Descriptor instead.
func (*AssignUserResponse) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{16}
}

func (x *AssignUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      int32                  `protobuf:"varint,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateStatusRequest) GetTicketId() int32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Type Messages
type CreateTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TeamId        int32                  `protobuf:"varint,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTypeRequest) Reset() {
	*x = CreateTypeRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTypeRequest) ProtoMessage() {}

func (x *CreateTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateTypeRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{19}
}

func (x *CreateTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTypeRequest) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *CreateTypeRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        int32                  `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTypeRequest) Reset() {
	*x = GetTypeRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeRequest) ProtoMessage() {}

func (x *GetTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeRequest.ProtoReflect.Descriptor instead.
func (*GetTypeRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{20}
}

func (x *GetTypeRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

type ListTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTypesRequest) Reset() {
	*x = ListTypesRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypesRequest) ProtoMessage() {}

func (x *ListTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypesRequest.ProtoReflect.Descriptor instead.
func (*ListTypesRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{21}
}

func (x *ListTypesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*TypeResponse        `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTypesResponse) Reset() {
	*x = ListTypesResponse{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypesResponse) ProtoMessage() {}

func (x *ListTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypesResponse.ProtoReflect.Descriptor instead.
func (*ListTypesResponse) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{22}
}

func (x *ListTypesResponse) GetTypes() []*TypeResponse {
	if x != nil {
		return x.Types
	}
	return nil
}

type UpdateTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        int32                  `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTypeRequest) Reset() {
	*x = UpdateTypeRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypeRequest) ProtoMessage() {}

func (x *UpdateTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateTypeRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateTypeRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *UpdateTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTypeRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DeleteTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        int32                  `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTypeRequest) Reset() {
	*x = DeleteTypeRequest{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTypeRequest) ProtoMessage() {}

func (x *DeleteTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteTypeRequest) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteTypeRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

type DeleteTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTicketResponse) Reset() {
	*x = DeleteTicketResponse{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTicketResponse) ProtoMessage() {}

func (x *DeleteTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTicketResponse.ProtoReflect.Descriptor instead.
func (*DeleteTicketResponse) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteTicketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTypeResponse) Reset() {
	*x = DeleteTypeResponse{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTypeResponse) ProtoMessage() {}

func (x *DeleteTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTypeResponse.ProtoReflect.Descriptor instead.
func (*DeleteTypeResponse) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteTypeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TeamId        int32                  `protobuf:"varint,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeResponse) Reset() {
	*x = TypeResponse{}
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeResponse) ProtoMessage() {}

func (x *TypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_helpdesk_proto_helpdesk_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeResponse.ProtoReflect.Descriptor instead.
func (*TypeResponse) Descriptor() ([]byte, []int) {
	return file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP(), []int{27}
}

func (x *TypeResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TypeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TypeResponse) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *TypeResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_services_helpdesk_proto_helpdesk_proto protoreflect.FileDescriptor

const file_services_helpdesk_proto_helpdesk_proto_rawDesc = "" +
	"\n" +
	"&services/helpdesk/proto/helpdesk.proto\x12\bhelpdesk\"\xee\x01\n" +
	"\x13CreateTicketRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12)\n" +
	"\x11help_desk_type_id\x18\x03 \x01(\x05R\x0ehelpDeskTypeId\x12$\n" +
	"\x0eportal_user_id\x18\x04 \x01(\x05R\fportalUserId\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x05R\bparentId\x12\x1d\n" +
	"\n" +
	"project_id\x18\a \x01(\x05R\tprojectId\"/\n" +
	"\x10GetTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x05R\bticketId\"\xa9\x01\n" +
	"\x13UpdateTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x05R\bticketId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12)\n" +
	"\x11help_desk_type_id\x18\x05 \x01(\x05R\x0ehelpDeskTypeId\"t\n" +
	"\x12ListTicketsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"\x90\x01\n" +
	"\x13ListTicketsResponse\x122\n" +
	"\atickets\x18\x01 \x03(\v2\x18.helpdesk.TicketResponseR\atickets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"2\n" +
	"\x13DeleteTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x05R\bticketId\"\xbd\x02\n" +
	"\x0eTicketResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcreate_date\x18\x03 \x01(\tR\n" +
	"createDate\x12)\n" +
	"\x11help_desk_type_id\x18\x04 \x01(\x05R\x0ehelpDeskTypeId\x12$\n" +
	"\x0eportal_user_id\x18\x05 \x01(\x05R\fportalUserId\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12!\n" +
	"\fresolve_date\x18\b \x01(\tR\vresolveDate\x12\x1b\n" +
	"\tparent_id\x18\t \x01(\x05R\bparentId\x12\x1d\n" +
	"\n" +
	"project_id\x18\n" +
	" \x01(\x05R\tprojectId\"c\n" +
	"\x11AddCommentRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x05R\bticketId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"1\n" +
	"\x12GetCommentsRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x05R\bticketId\"L\n" +
	"\x13GetCommentsResponse\x125\n" +
	"\bcomments\x18\x01 \x03(\v2\x19.helpdesk.CommentResponseR\bcomments\"\x90\x01\n" +
	"\x0fCommentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\x05R\bticketId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x86\x01\n" +
	"\x14AddAttachmentRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x05R\bticketId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12#\n" +
	"\rdocument_type\x18\x04 \x01(\tR\fdocumentType\"4\n" +
	"\x15GetAttachmentsRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x05R\bticketId\"X\n" +
	"\x16GetAttachmentsResponse\x12>\n" +
	"\vattachments\x18\x01 \x03(\v2\x1c.helpdesk.AttachmentResponseR\vattachments\"\x99\x01\n" +
	"\x12AttachmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\x05R\bticketId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rdocument_type\x18\x04 \x01(\tR\fdocumentType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"I\n" +
	"\x11AssignUserRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x05R\bticketId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\".\n" +
	"\x12AssignUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x13UpdateStatusRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\x05R\bticketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"0\n" +
	"\x14UpdateStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x7f\n" +
	"\x11CreateTypeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\x05R\x06teamId\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\")\n" +
	"\x0eGetTypeRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\x05R\x06typeId\"3\n" +
	"\x10ListTypesRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\"A\n" +
	"\x11ListTypesResponse\x12,\n" +
	"\x05types\x18\x01 \x03(\v2\x16.helpdesk.TypeResponseR\x05types\"\x7f\n" +
	"\x11UpdateTypeRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\x05R\x06typeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\",\n" +
	"\x11DeleteTypeRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\x05R\x06typeId\"0\n" +
	"\x14DeleteTicketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x12DeleteTypeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8a\x01\n" +
	"\fTypeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\ateam_id\x18\x04 \x01(\x05R\x06teamId\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive2\x81\x03\n" +
	"\x0fHelpDeskService\x12G\n" +
	"\fCreateTicket\x12\x1d.helpdesk.CreateTicketRequest\x1a\x18.helpdesk.TicketResponse\x12A\n" +
	"\tGetTicket\x12\x1a.helpdesk.GetTicketRequest\x1a\x18.helpdesk.TicketResponse\x12G\n" +
	"\fUpdateTicket\x12\x1d.helpdesk.UpdateTicketRequest\x1a\x18.helpdesk.TicketResponse\x12J\n" +
	"\vListTickets\x12\x1c.helpdesk.ListTicketsRequest\x1a\x1d.helpdesk.ListTicketsResponse\x12M\n" +
	"\fDeleteTicket\x12\x1d.helpdesk.DeleteTicketRequest\x1a\x1e.helpdesk.DeleteTicketResponse2\xdd\x03\n" +
	"\rTicketService\x12D\n" +
	"\n" +
	"AddComment\x12\x1b.helpdesk.AddCommentRequest\x1a\x19.helpdesk.CommentResponse\x12J\n" +
	"\vGetComments\x12\x1c.helpdesk.GetCommentsRequest\x1a\x1d.helpdesk.GetCommentsResponse\x12M\n" +
	"\rAddAttachment\x12\x1e.helpdesk.AddAttachmentRequest\x1a\x1c.helpdesk.AttachmentResponse\x12S\n" +
	"\x0eGetAttachments\x12\x1f.helpdesk.GetAttachmentsRequest\x1a .helpdesk.GetAttachmentsResponse\x12G\n" +
	"\n" +
	"AssignUser\x12\x1b.helpdesk.AssignUserRequest\x1a\x1c.helpdesk.AssignUserResponse\x12M\n" +
	"\fUpdateStatus\x12\x1d.helpdesk.UpdateStatusRequest\x1a\x1e.helpdesk.UpdateStatusResponse2\xe7\x02\n" +
	"\x13HelpDeskTypeService\x12A\n" +
	"\n" +
	"CreateType\x12\x1b.helpdesk.CreateTypeRequest\x1a\x16.helpdesk.TypeResponse\x12;\n" +
	"\aGetType\x12\x18.helpdesk.GetTypeRequest\x1a\x16.helpdesk.TypeResponse\x12D\n" +
	"\tListTypes\x12\x1a.helpdesk.ListTypesRequest\x1a\x1b.helpdesk.ListTypesResponse\x12A\n" +
	"\n" +
	"UpdateType\x12\x1b.helpdesk.UpdateTypeRequest\x1a\x16.helpdesk.TypeResponse\x12G\n" +
	"\n" +
	"DeleteType\x12\x1b.helpdesk.DeleteTypeRequest\x1a\x1c.helpdesk.DeleteTypeResponseB!Z\x1fbackend/services/helpdesk/protob\x06proto3"

var (
	file_services_helpdesk_proto_helpdesk_proto_rawDescOnce sync.Once
	file_services_helpdesk_proto_helpdesk_proto_rawDescData []byte
)

func file_services_helpdesk_proto_helpdesk_proto_rawDescGZIP() []byte {
	file_services_helpdesk_proto_helpdesk_proto_rawDescOnce.Do(func() {
		file_services_helpdesk_proto_helpdesk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_helpdesk_proto_helpdesk_proto_rawDesc), len(file_services_helpdesk_proto_helpdesk_proto_rawDesc)))
	})
	return file_services_helpdesk_proto_helpdesk_proto_rawDescData
}

var file_services_helpdesk_proto_helpdesk_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_services_helpdesk_proto_helpdesk_proto_goTypes = []any{
	(*CreateTicketRequest)(nil),    // 0: helpdesk.CreateTicketRequest
	(*GetTicketRequest)(nil),       // 1: helpdesk.GetTicketRequest
	(*UpdateTicketRequest)(nil),    // 2: helpdesk.UpdateTicketRequest
	(*ListTicketsRequest)(nil),     // 3: helpdesk.ListTicketsRequest
	(*ListTicketsResponse)(nil),    // 4: helpdesk.ListTicketsResponse
	(*DeleteTicketRequest)(nil),    // 5: helpdesk.DeleteTicketRequest
	(*TicketResponse)(nil),         // 6: helpdesk.TicketResponse
	(*AddCommentRequest)(nil),      // 7: helpdesk.AddCommentRequest
	(*GetCommentsRequest)(nil),     // 8: helpdesk.GetCommentsRequest
	(*GetCommentsResponse)(nil),    // 9: helpdesk.GetCommentsResponse
	(*CommentResponse)(nil),        // 10: helpdesk.CommentResponse
	(*AddAttachmentRequest)(nil),   // 11: helpdesk.AddAttachmentRequest
	(*GetAttachmentsRequest)(nil),  // 12: helpdesk.GetAttachmentsRequest
	(*GetAttachmentsResponse)(nil), // 13: helpdesk.GetAttachmentsResponse
	(*AttachmentResponse)(nil),     // 14: helpdesk.AttachmentResponse
	(*AssignUserRequest)(nil),      // 15: helpdesk.AssignUserRequest
	(*AssignUserResponse)(nil),     // 16: helpdesk.AssignUserResponse
	(*UpdateStatusRequest)(nil),    // 17: helpdesk.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),   // 18: helpdesk.UpdateStatusResponse
	(*CreateTypeRequest)(nil),      // 19: helpdesk.CreateTypeRequest
	(*GetTypeRequest)(nil),         // 20: helpdesk.GetTypeRequest
	(*ListTypesRequest)(nil),       // 21: helpdesk.ListTypesRequest
	(*ListTypesResponse)(nil),      // 22: helpdesk.ListTypesResponse
	(*UpdateTypeRequest)(nil),      // 23: helpdesk.UpdateTypeRequest
	(*DeleteTypeRequest)(nil),      // 24: helpdesk.DeleteTypeRequest
	(*DeleteTicketResponse)(nil),   // 25: helpdesk.DeleteTicketResponse
	(*DeleteTypeResponse)(nil),     // 26: helpdesk.DeleteTypeResponse
	(*TypeResponse)(nil),           // 27: helpdesk.TypeResponse
}
var file_services_helpdesk_proto_helpdesk_proto_depIdxs = []int32{
	6,  // 0: helpdesk.ListTicketsResponse.tickets:type_name -> helpdesk.TicketResponse
	10, // 1: helpdesk.GetCommentsResponse.comments:type_name -> helpdesk.CommentResponse
	14, // 2: helpdesk.GetAttachmentsResponse.attachments:type_name -> helpdesk.AttachmentResponse
	27, // 3: helpdesk.ListTypesResponse.types:type_name -> helpdesk.TypeResponse
	0,  // 4: helpdesk.HelpDeskService.CreateTicket:input_type -> helpdesk.CreateTicketRequest
	1,  // 5: helpdesk.HelpDeskService.GetTicket:input_type -> helpdesk.GetTicketRequest
	2,  // 6: helpdesk.HelpDeskService.UpdateTicket:input_type -> helpdesk.UpdateTicketRequest
	3,  // 7: helpdesk.HelpDeskService.ListTickets:input_type -> helpdesk.ListTicketsRequest
	5,  // 8: helpdesk.HelpDeskService.DeleteTicket:input_type -> helpdesk.DeleteTicketRequest
	7,  // 9: helpdesk.TicketService.AddComment:input_type -> helpdesk.AddCommentRequest
	8,  // 10: helpdesk.TicketService.GetComments:input_type -> helpdesk.GetCommentsRequest
	11, // 11: helpdesk.TicketService.AddAttachment:input_type -> helpdesk.AddAttachmentRequest
	12, // 12: helpdesk.TicketService.GetAttachments:input_type -> helpdesk.GetAttachmentsRequest
	15, // 13: helpdesk.TicketService.AssignUser:input_type -> helpdesk.AssignUserRequest
	17, // 14: helpdesk.TicketService.UpdateStatus:input_type -> helpdesk.UpdateStatusRequest
	19, // 15: helpdesk.HelpDeskTypeService.CreateType:input_type -> helpdesk.CreateTypeRequest
	20, // 16: helpdesk.HelpDeskTypeService.GetType:input_type -> helpdesk.GetTypeRequest
	21, // 17: helpdesk.HelpDeskTypeService.ListTypes:input_type -> helpdesk.ListTypesRequest
	23, // 18: helpdesk.HelpDeskTypeService.UpdateType:input_type -> helpdesk.UpdateTypeRequest
	24, // 19: helpdesk.HelpDeskTypeService.DeleteType:input_type -> helpdesk.DeleteTypeRequest
	6,  // 20: helpdesk.HelpDeskService.CreateTicket:output_type -> helpdesk.TicketResponse
	6,  // 21: helpdesk.HelpDeskService.GetTicket:output_type -> helpdesk.TicketResponse
	6,  // 22: helpdesk.HelpDeskService.UpdateTicket:output_type -> helpdesk.TicketResponse
	4,  // 23: helpdesk.HelpDeskService.ListTickets:output_type -> helpdesk.ListTicketsResponse
	25, // 24: helpdesk.HelpDeskService.DeleteTicket:output_type -> helpdesk.DeleteTicketResponse
	10, // 25: helpdesk.TicketService.AddComment:output_type -> helpdesk.CommentResponse
	9,  // 26: helpdesk.TicketService.GetComments:output_type -> helpdesk.GetCommentsResponse
	14, // 27: helpdesk.TicketService.AddAttachment:output_type -> helpdesk.AttachmentResponse
	13, // 28: helpdesk.TicketService.GetAttachments:output_type -> helpdesk.GetAttachmentsResponse
	16, // 29: helpdesk.TicketService.AssignUser:output_type -> helpdesk.AssignUserResponse
	18, // 30: helpdesk.TicketService.UpdateStatus:output_type -> helpdesk.UpdateStatusResponse
	27, // 31: helpdesk.HelpDeskTypeService.CreateType:output_type -> helpdesk.TypeResponse
	27, // 32: helpdesk.HelpDeskTypeService.GetType:output_type -> helpdesk.TypeResponse
	22, // 33: helpdesk.HelpDeskTypeService.ListTypes:output_type -> helpdesk.ListTypesResponse
	27, // 34: helpdesk.HelpDeskTypeService.UpdateType:output_type -> helpdesk.TypeResponse
	26, // 35: helpdesk.HelpDeskTypeService.DeleteType:output_type -> helpdesk.DeleteTypeResponse
	20, // [20:36] is the sub-list for method output_type
	4,  // [4:20] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_services_helpdesk_proto_helpdesk_proto_init() }
func file_services_helpdesk_proto_helpdesk_proto_init() {
	if File_services_helpdesk_proto_helpdesk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_helpdesk_proto_helpdesk_proto_rawDesc), len(file_services_helpdesk_proto_helpdesk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_services_helpdesk_proto_helpdesk_proto_goTypes,
		DependencyIndexes: file_services_helpdesk_proto_helpdesk_proto_depIdxs,
		MessageInfos:      file_services_helpdesk_proto_helpdesk_proto_msgTypes,
	}.Build()
	File_services_helpdesk_proto_helpdesk_proto = out.File
	file_services_helpdesk_proto_helpdesk_proto_goTypes = nil
	file_services_helpdesk_proto_helpdesk_proto_depIdxs = nil
}
