// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: services/helpdesk/proto/helpdesk.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HelpDeskService_CreateTicket_FullMethodName = "/helpdesk.HelpDeskService/CreateTicket"
	HelpDeskService_GetTicket_FullMethodName    = "/helpdesk.HelpDeskService/GetTicket"
	HelpDeskService_UpdateTicket_FullMethodName = "/helpdesk.HelpDeskService/UpdateTicket"
	HelpDeskService_ListTickets_FullMethodName  = "/helpdesk.HelpDeskService/ListTickets"
	HelpDeskService_DeleteTicket_FullMethodName = "/helpdesk.HelpDeskService/DeleteTicket"
)

// HelpDeskServiceClient is the client API for HelpDeskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Help Desk Service
type HelpDeskServiceClient interface {
	CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...grpc.CallOption) (*TicketResponse, error)
	GetTicket(ctx context.Context, in *GetTicketRequest, opts ...grpc.CallOption) (*TicketResponse, error)
	UpdateTicket(ctx context.Context, in *UpdateTicketRequest, opts ...grpc.CallOption) (*TicketResponse, error)
	ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error)
	DeleteTicket(ctx context.Context, in *DeleteTicketRequest, opts ...grpc.CallOption) (*DeleteTicketResponse, error)
}

type helpDeskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelpDeskServiceClient(cc grpc.ClientConnInterface) HelpDeskServiceClient {
	return &helpDeskServiceClient{cc}
}

func (c *helpDeskServiceClient) CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...grpc.CallOption) (*TicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketResponse)
	err := c.cc.Invoke(ctx, HelpDeskService_CreateTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helpDeskServiceClient) GetTicket(ctx context.Context, in *GetTicketRequest, opts ...grpc.CallOption) (*TicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketResponse)
	err := c.cc.Invoke(ctx, HelpDeskService_GetTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helpDeskServiceClient) UpdateTicket(ctx context.Context, in *UpdateTicketRequest, opts ...grpc.CallOption) (*TicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketResponse)
	err := c.cc.Invoke(ctx, HelpDeskService_UpdateTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helpDeskServiceClient) ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTicketsResponse)
	err := c.cc.Invoke(ctx, HelpDeskService_ListTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helpDeskServiceClient) DeleteTicket(ctx context.Context, in *DeleteTicketRequest, opts ...grpc.CallOption) (*DeleteTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTicketResponse)
	err := c.cc.Invoke(ctx, HelpDeskService_DeleteTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelpDeskServiceServer is the server API for HelpDeskService service.
// All implementations must embed UnimplementedHelpDeskServiceServer
// for forward compatibility.
//
// Help Desk Service
type HelpDeskServiceServer interface {
	CreateTicket(context.Context, *CreateTicketRequest) (*TicketResponse, error)
	GetTicket(context.Context, *GetTicketRequest) (*TicketResponse, error)
	UpdateTicket(context.Context, *UpdateTicketRequest) (*TicketResponse, error)
	ListTickets(context.Context, *ListTicketsRequest) (*ListTicketsResponse, error)
	DeleteTicket(context.Context, *DeleteTicketRequest) (*DeleteTicketResponse, error)
	mustEmbedUnimplementedHelpDeskServiceServer()
}

// UnimplementedHelpDeskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelpDeskServiceServer struct{}

func (UnimplementedHelpDeskServiceServer) CreateTicket(context.Context, *CreateTicketRequest) (*TicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTicket not implemented")
}
func (UnimplementedHelpDeskServiceServer) GetTicket(context.Context, *GetTicketRequest) (*TicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicket not implemented")
}
func (UnimplementedHelpDeskServiceServer) UpdateTicket(context.Context, *UpdateTicketRequest) (*TicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTicket not implemented")
}
func (UnimplementedHelpDeskServiceServer) ListTickets(context.Context, *ListTicketsRequest) (*ListTicketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTickets not implemented")
}
func (UnimplementedHelpDeskServiceServer) DeleteTicket(context.Context, *DeleteTicketRequest) (*DeleteTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTicket not implemented")
}
func (UnimplementedHelpDeskServiceServer) mustEmbedUnimplementedHelpDeskServiceServer() {}
func (UnimplementedHelpDeskServiceServer) testEmbeddedByValue()                         {}

// UnsafeHelpDeskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelpDeskServiceServer will
// result in compilation errors.
type UnsafeHelpDeskServiceServer interface {
	mustEmbedUnimplementedHelpDeskServiceServer()
}

func RegisterHelpDeskServiceServer(s grpc.ServiceRegistrar, srv HelpDeskServiceServer) {
	// If the following call panics, it indicates UnimplementedHelpDeskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HelpDeskService_ServiceDesc, srv)
}

func _HelpDeskService_CreateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDeskServiceServer).CreateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDeskService_CreateTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDeskServiceServer).CreateTicket(ctx, req.(*CreateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelpDeskService_GetTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDeskServiceServer).GetTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDeskService_GetTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDeskServiceServer).GetTicket(ctx, req.(*GetTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelpDeskService_UpdateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDeskServiceServer).UpdateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDeskService_UpdateTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDeskServiceServer).UpdateTicket(ctx, req.(*UpdateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelpDeskService_ListTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDeskServiceServer).ListTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDeskService_ListTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDeskServiceServer).ListTickets(ctx, req.(*ListTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelpDeskService_DeleteTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDeskServiceServer).DeleteTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDeskService_DeleteTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDeskServiceServer).DeleteTicket(ctx, req.(*DeleteTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelpDeskService_ServiceDesc is the grpc.ServiceDesc for HelpDeskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelpDeskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helpdesk.HelpDeskService",
	HandlerType: (*HelpDeskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTicket",
			Handler:    _HelpDeskService_CreateTicket_Handler,
		},
		{
			MethodName: "GetTicket",
			Handler:    _HelpDeskService_GetTicket_Handler,
		},
		{
			MethodName: "UpdateTicket",
			Handler:    _HelpDeskService_UpdateTicket_Handler,
		},
		{
			MethodName: "ListTickets",
			Handler:    _HelpDeskService_ListTickets_Handler,
		},
		{
			MethodName: "DeleteTicket",
			Handler:    _HelpDeskService_DeleteTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/helpdesk/proto/helpdesk.proto",
}

const (
	TicketService_AddComment_FullMethodName     = "/helpdesk.TicketService/AddComment"
	TicketService_GetComments_FullMethodName    = "/helpdesk.TicketService/GetComments"
	TicketService_AddAttachment_FullMethodName  = "/helpdesk.TicketService/AddAttachment"
	TicketService_GetAttachments_FullMethodName = "/helpdesk.TicketService/GetAttachments"
	TicketService_AssignUser_FullMethodName     = "/helpdesk.TicketService/AssignUser"
	TicketService_UpdateStatus_FullMethodName   = "/helpdesk.TicketService/UpdateStatus"
)

// TicketServiceClient is the client API for TicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Ticket Service
type TicketServiceClient interface {
	AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
	GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error)
	AddAttachment(ctx context.Context, in *AddAttachmentRequest, opts ...grpc.CallOption) (*AttachmentResponse, error)
	GetAttachments(ctx context.Context, in *GetAttachmentsRequest, opts ...grpc.CallOption) (*GetAttachmentsResponse, error)
	AssignUser(ctx context.Context, in *AssignUserRequest, opts ...grpc.CallOption) (*AssignUserResponse, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error)
}

type ticketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketServiceClient(cc grpc.ClientConnInterface) TicketServiceClient {
	return &ticketServiceClient{cc}
}

func (c *ticketServiceClient) AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, TicketService_AddComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommentsResponse)
	err := c.cc.Invoke(ctx, TicketService_GetComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) AddAttachment(ctx context.Context, in *AddAttachmentRequest, opts ...grpc.CallOption) (*AttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachmentResponse)
	err := c.cc.Invoke(ctx, TicketService_AddAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetAttachments(ctx context.Context, in *GetAttachmentsRequest, opts ...grpc.CallOption) (*GetAttachmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttachmentsResponse)
	err := c.cc.Invoke(ctx, TicketService_GetAttachments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) AssignUser(ctx context.Context, in *AssignUserRequest, opts ...grpc.CallOption) (*AssignUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignUserResponse)
	err := c.cc.Invoke(ctx, TicketService_AssignUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStatusResponse)
	err := c.cc.Invoke(ctx, TicketService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServiceServer is the server API for TicketService service.
// All implementations must embed UnimplementedTicketServiceServer
// for forward compatibility.
//
// Ticket Service
type TicketServiceServer interface {
	AddComment(context.Context, *AddCommentRequest) (*CommentResponse, error)
	GetComments(context.Context, *GetCommentsRequest) (*GetCommentsResponse, error)
	AddAttachment(context.Context, *AddAttachmentRequest) (*AttachmentResponse, error)
	GetAttachments(context.Context, *GetAttachmentsRequest) (*GetAttachmentsResponse, error)
	AssignUser(context.Context, *AssignUserRequest) (*AssignUserResponse, error)
	UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error)
	mustEmbedUnimplementedTicketServiceServer()
}

// UnimplementedTicketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTicketServiceServer struct{}

func (UnimplementedTicketServiceServer) AddComment(context.Context, *AddCommentRequest) (*CommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddComment not implemented")
}
func (UnimplementedTicketServiceServer) GetComments(context.Context, *GetCommentsRequest) (*GetCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComments not implemented")
}
func (UnimplementedTicketServiceServer) AddAttachment(context.Context, *AddAttachmentRequest) (*AttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAttachment not implemented")
}
func (UnimplementedTicketServiceServer) GetAttachments(context.Context, *GetAttachmentsRequest) (*GetAttachmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttachments not implemented")
}
func (UnimplementedTicketServiceServer) AssignUser(context.Context, *AssignUserRequest) (*AssignUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignUser not implemented")
}
func (UnimplementedTicketServiceServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedTicketServiceServer) mustEmbedUnimplementedTicketServiceServer() {}
func (UnimplementedTicketServiceServer) testEmbeddedByValue()                       {}

// UnsafeTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketServiceServer will
// result in compilation errors.
type UnsafeTicketServiceServer interface {
	mustEmbedUnimplementedTicketServiceServer()
}

func RegisterTicketServiceServer(s grpc.ServiceRegistrar, srv TicketServiceServer) {
	// If the following call panics, it indicates UnimplementedTicketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TicketService_ServiceDesc, srv)
}

func _TicketService_AddComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).AddComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_AddComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).AddComment(ctx, req.(*AddCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetComments(ctx, req.(*GetCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_AddAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).AddAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_AddAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).AddAttachment(ctx, req.(*AddAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetAttachments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetAttachments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetAttachments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetAttachments(ctx, req.(*GetAttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_AssignUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).AssignUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_AssignUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).AssignUser(ctx, req.(*AssignUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketService_ServiceDesc is the grpc.ServiceDesc for TicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helpdesk.TicketService",
	HandlerType: (*TicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddComment",
			Handler:    _TicketService_AddComment_Handler,
		},
		{
			MethodName: "GetComments",
			Handler:    _TicketService_GetComments_Handler,
		},
		{
			MethodName: "AddAttachment",
			Handler:    _TicketService_AddAttachment_Handler,
		},
		{
			MethodName: "GetAttachments",
			Handler:    _TicketService_GetAttachments_Handler,
		},
		{
			MethodName: "AssignUser",
			Handler:    _TicketService_AssignUser_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _TicketService_UpdateStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/helpdesk/proto/helpdesk.proto",
}

const (
	HelpDeskTypeService_CreateType_FullMethodName = "/helpdesk.HelpDeskTypeService/CreateType"
	HelpDeskTypeService_GetType_FullMethodName    = "/helpdesk.HelpDeskTypeService/GetType"
	HelpDeskTypeService_ListTypes_FullMethodName  = "/helpdesk.HelpDeskTypeService/ListTypes"
	HelpDeskTypeService_UpdateType_FullMethodName = "/helpdesk.HelpDeskTypeService/UpdateType"
	HelpDeskTypeService_DeleteType_FullMethodName = "/helpdesk.HelpDeskTypeService/DeleteType"
)

// HelpDeskTypeServiceClient is the client API for HelpDeskTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Help Desk Type Service
type HelpDeskTypeServiceClient interface {
	CreateType(ctx context.Context, in *CreateTypeRequest, opts ...grpc.CallOption) (*TypeResponse, error)
	GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*TypeResponse, error)
	ListTypes(ctx context.Context, in *ListTypesRequest, opts ...grpc.CallOption) (*ListTypesResponse, error)
	UpdateType(ctx context.Context, in *UpdateTypeRequest, opts ...grpc.CallOption) (*TypeResponse, error)
	DeleteType(ctx context.Context, in *DeleteTypeRequest, opts ...grpc.CallOption) (*DeleteTypeResponse, error)
}

type helpDeskTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelpDeskTypeServiceClient(cc grpc.ClientConnInterface) HelpDeskTypeServiceClient {
	return &helpDeskTypeServiceClient{cc}
}

func (c *helpDeskTypeServiceClient) CreateType(ctx context.Context, in *CreateTypeRequest, opts ...grpc.CallOption) (*TypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeResponse)
	err := c.cc.Invoke(ctx, HelpDeskTypeService_CreateType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helpDeskTypeServiceClient) GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*TypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeResponse)
	err := c.cc.Invoke(ctx, HelpDeskTypeService_GetType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helpDeskTypeServiceClient) ListTypes(ctx context.Context, in *ListTypesRequest, opts ...grpc.CallOption) (*ListTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTypesResponse)
	err := c.cc.Invoke(ctx, HelpDeskTypeService_ListTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helpDeskTypeServiceClient) UpdateType(ctx context.Context, in *UpdateTypeRequest, opts ...grpc.CallOption) (*TypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeResponse)
	err := c.cc.Invoke(ctx, HelpDeskTypeService_UpdateType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helpDeskTypeServiceClient) DeleteType(ctx context.Context, in *DeleteTypeRequest, opts ...grpc.CallOption) (*DeleteTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTypeResponse)
	err := c.cc.Invoke(ctx, HelpDeskTypeService_DeleteType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelpDeskTypeServiceServer is the server API for HelpDeskTypeService service.
// All implementations must embed UnimplementedHelpDeskTypeServiceServer
// for forward compatibility.
//
// Help Desk Type Service
type HelpDeskTypeServiceServer interface {
	CreateType(context.Context, *CreateTypeRequest) (*TypeResponse, error)
	GetType(context.Context, *GetTypeRequest) (*TypeResponse, error)
	ListTypes(context.Context, *ListTypesRequest) (*ListTypesResponse, error)
	UpdateType(context.Context, *UpdateTypeRequest) (*TypeResponse, error)
	DeleteType(context.Context, *DeleteTypeRequest) (*DeleteTypeResponse, error)
	mustEmbedUnimplementedHelpDeskTypeServiceServer()
}

// UnimplementedHelpDeskTypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelpDeskTypeServiceServer struct{}

func (UnimplementedHelpDeskTypeServiceServer) CreateType(context.Context, *CreateTypeRequest) (*TypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateType not implemented")
}
func (UnimplementedHelpDeskTypeServiceServer) GetType(context.Context, *GetTypeRequest) (*TypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetType not implemented")
}
func (UnimplementedHelpDeskTypeServiceServer) ListTypes(context.Context, *ListTypesRequest) (*ListTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTypes not implemented")
}
func (UnimplementedHelpDeskTypeServiceServer) UpdateType(context.Context, *UpdateTypeRequest) (*TypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateType not implemented")
}
func (UnimplementedHelpDeskTypeServiceServer) DeleteType(context.Context, *DeleteTypeRequest) (*DeleteTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteType not implemented")
}
func (UnimplementedHelpDeskTypeServiceServer) mustEmbedUnimplementedHelpDeskTypeServiceServer() {}
func (UnimplementedHelpDeskTypeServiceServer) testEmbeddedByValue()                             {}

// UnsafeHelpDeskTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelpDeskTypeServiceServer will
// result in compilation errors.
type UnsafeHelpDeskTypeServiceServer interface {
	mustEmbedUnimplementedHelpDeskTypeServiceServer()
}

func RegisterHelpDeskTypeServiceServer(s grpc.ServiceRegistrar, srv HelpDeskTypeServiceServer) {
	// If the following call panics, it indicates UnimplementedHelpDeskTypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HelpDeskTypeService_ServiceDesc, srv)
}

func _HelpDeskTypeService_CreateType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDeskTypeServiceServer).CreateType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDeskTypeService_CreateType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDeskTypeServiceServer).CreateType(ctx, req.(*CreateTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelpDeskTypeService_GetType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDeskTypeServiceServer).GetType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDeskTypeService_GetType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDeskTypeServiceServer).GetType(ctx, req.(*GetTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelpDeskTypeService_ListTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDeskTypeServiceServer).ListTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDeskTypeService_ListTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDeskTypeServiceServer).ListTypes(ctx, req.(*ListTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelpDeskTypeService_UpdateType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDeskTypeServiceServer).UpdateType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDeskTypeService_UpdateType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDeskTypeServiceServer).UpdateType(ctx, req.(*UpdateTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelpDeskTypeService_DeleteType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpDeskTypeServiceServer).DeleteType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelpDeskTypeService_DeleteType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpDeskTypeServiceServer).DeleteType(ctx, req.(*DeleteTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelpDeskTypeService_ServiceDesc is the grpc.ServiceDesc for HelpDeskTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelpDeskTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helpdesk.HelpDeskTypeService",
	HandlerType: (*HelpDeskTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateType",
			Handler:    _HelpDeskTypeService_CreateType_Handler,
		},
		{
			MethodName: "GetType",
			Handler:    _HelpDeskTypeService_GetType_Handler,
		},
		{
			MethodName: "ListTypes",
			Handler:    _HelpDeskTypeService_ListTypes_Handler,
		},
		{
			MethodName: "UpdateType",
			Handler:    _HelpDeskTypeService_UpdateType_Handler,
		},
		{
			MethodName: "DeleteType",
			Handler:    _HelpDeskTypeService_DeleteType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/helpdesk/proto/helpdesk.proto",
}
