// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: services/client-container/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Device Registration Messages
type RegisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsType        string                 `protobuf:"bytes,3,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Architecture  string                 `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	IpAddress     string                 `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	DeviceSerial  string                 `protobuf:"bytes,7,opt,name=device_serial,json=deviceSerial,proto3" json:"device_serial,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,8,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	CsrPem        string                 `protobuf:"bytes,9,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	HardwareInfo  map[string]string      `protobuf:"bytes,10,rep,name=hardware_info,json=hardwareInfo,proto3" json:"hardware_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterDeviceRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterDeviceRequest) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *RegisterDeviceRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterDeviceRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *RegisterDeviceRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterDeviceRequest) GetDeviceSerial() string {
	if x != nil {
		return x.DeviceSerial
	}
	return ""
}

func (x *RegisterDeviceRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterDeviceRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *RegisterDeviceRequest) GetHardwareInfo() map[string]string {
	if x != nil {
		return x.HardwareInfo
	}
	return nil
}

type RegisterDeviceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeviceId         int32                  `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	VerificationCode string                 `protobuf:"bytes,3,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterDeviceResponse) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *RegisterDeviceResponse) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *RegisterDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyDeviceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	CsrPem           string                 `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyDeviceRequest) Reset() {
	*x = VerifyDeviceRequest{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyDeviceRequest) ProtoMessage() {}

func (x *VerifyDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyDeviceRequest.ProtoReflect.Descriptor instead.
func (*VerifyDeviceRequest) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyDeviceRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *VerifyDeviceRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *VerifyDeviceRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

type VerifyDeviceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CertificatePem    string                 `protobuf:"bytes,2,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	CertificateSerial string                 `protobuf:"bytes,3,opt,name=certificate_serial,json=certificateSerial,proto3" json:"certificate_serial,omitempty"`
	ContainerId       string                 `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Message           string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyDeviceResponse) Reset() {
	*x = VerifyDeviceResponse{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyDeviceResponse) ProtoMessage() {}

func (x *VerifyDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyDeviceResponse.ProtoReflect.Descriptor instead.
func (*VerifyDeviceResponse) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyDeviceResponse) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *VerifyDeviceResponse) GetCertificateSerial() string {
	if x != nil {
		return x.CertificateSerial
	}
	return ""
}

func (x *VerifyDeviceResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *VerifyDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Health Reporting Messages
type HealthReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Status        *AgentStatus           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	PluginHealth  []*PluginHealth        `protobuf:"bytes,4,rep,name=plugin_health,json=pluginHealth,proto3" json:"plugin_health,omitempty"`
	Metrics       *SystemMetrics         `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HealthReport) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *HealthReport) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HealthReport) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HealthReport) GetPluginHealth() []*PluginHealth {
	if x != nil {
		return x.PluginHealth
	}
	return nil
}

func (x *HealthReport) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HealthReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // active, inactive, error
	LastError     string                 `protobuf:"bytes,2,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AgentStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *AgentStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type PluginHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // active, inactive, error
	Healthy       bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	LastError     string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginHealth) Reset() {
	*x = PluginHealth{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginHealth) ProtoMessage() {}

func (x *PluginHealth) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginHealth.ProtoReflect.Descriptor instead.
func (*PluginHealth) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *PluginHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginHealth) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginHealth) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PluginHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *PluginHealth) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type SystemMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent  float64                `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsedBytes  int64                  `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes int64                  `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskUsedBytes    int64                  `protobuf:"varint,4,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes   int64                  `protobuf:"varint,5,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SystemMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *SystemMetrics) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *SystemMetrics) GetDiskUsedBytes() int64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *SystemMetrics) GetDiskTotalBytes() int64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

type HealthResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Success                   bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message                   string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NextReportIntervalSeconds int64                  `protobuf:"varint,3,opt,name=next_report_interval_seconds,json=nextReportIntervalSeconds,proto3" json:"next_report_interval_seconds,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetNextReportIntervalSeconds() int64 {
	if x != nil {
		return x.NextReportIntervalSeconds
	}
	return 0
}

// Configuration Messages
type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"` // Empty means all config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ConfigRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Configuration map[string]string      `protobuf:"bytes,2,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigResponse) GetConfiguration() map[string]string {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *ConfigResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Configuration map[string]string      `protobuf:"bytes,2,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateConfigRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *UpdateConfigRequest) GetConfiguration() map[string]string {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// Plugin Management Messages
type PluginListRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	IncludeInactive bool                   `protobuf:"varint,2,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginListRequest) Reset() {
	*x = PluginListRequest{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginListRequest) ProtoMessage() {}

func (x *PluginListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginListRequest.ProtoReflect.Descriptor instead.
func (*PluginListRequest) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *PluginListRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *PluginListRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

type PluginListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Plugins       []*PluginInfo          `protobuf:"bytes,2,rep,name=plugins,proto3" json:"plugins,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginListResponse) Reset() {
	*x = PluginListResponse{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginListResponse) ProtoMessage() {}

func (x *PluginListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginListResponse.ProtoReflect.Descriptor instead.
func (*PluginListResponse) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *PluginListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PluginListResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *PluginListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // installed, active, inactive, error
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InstallPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // Empty means latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPluginRequest) Reset() {
	*x = InstallPluginRequest{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginRequest) ProtoMessage() {}

func (x *InstallPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPluginRequest.ProtoReflect.Descriptor instead.
func (*InstallPluginRequest) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *InstallPluginRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *InstallPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *InstallPluginRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InstallPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPluginResponse) Reset() {
	*x = InstallPluginResponse{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginResponse) ProtoMessage() {}

func (x *InstallPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPluginResponse.ProtoReflect.Descriptor instead.
func (*InstallPluginResponse) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *InstallPluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstallPluginResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *InstallPluginResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallPluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UninstallPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallPluginRequest) Reset() {
	*x = UninstallPluginRequest{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallPluginRequest) ProtoMessage() {}

func (x *UninstallPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallPluginRequest.ProtoReflect.Descriptor instead.
func (*UninstallPluginRequest) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *UninstallPluginRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *UninstallPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

type UninstallPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallPluginResponse) Reset() {
	*x = UninstallPluginResponse{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallPluginResponse) ProtoMessage() {}

func (x *UninstallPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallPluginResponse.ProtoReflect.Descriptor instead.
func (*UninstallPluginResponse) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *UninstallPluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UninstallPluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ActivatePluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivatePluginRequest) Reset() {
	*x = ActivatePluginRequest{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivatePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivatePluginRequest) ProtoMessage() {}

func (x *ActivatePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivatePluginRequest.ProtoReflect.Descriptor instead.
func (*ActivatePluginRequest) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ActivatePluginRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ActivatePluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *ActivatePluginRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ActivatePluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivatePluginResponse) Reset() {
	*x = ActivatePluginResponse{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivatePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivatePluginResponse) ProtoMessage() {}

func (x *ActivatePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivatePluginResponse.ProtoReflect.Descriptor instead.
func (*ActivatePluginResponse) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ActivatePluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActivatePluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeactivatePluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivatePluginRequest) Reset() {
	*x = DeactivatePluginRequest{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivatePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivatePluginRequest) ProtoMessage() {}

func (x *DeactivatePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivatePluginRequest.ProtoReflect.Descriptor instead.
func (*DeactivatePluginRequest) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *DeactivatePluginRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeactivatePluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

type DeactivatePluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivatePluginResponse) Reset() {
	*x = DeactivatePluginResponse{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivatePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivatePluginResponse) ProtoMessage() {}

func (x *DeactivatePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivatePluginResponse.ProtoReflect.Descriptor instead.
func (*DeactivatePluginResponse) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{22}
}

func (x *DeactivatePluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeactivatePluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PluginStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStatusRequest) Reset() {
	*x = PluginStatusRequest{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatusRequest) ProtoMessage() {}

func (x *PluginStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatusRequest.ProtoReflect.Descriptor instead.
func (*PluginStatusRequest) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{23}
}

func (x *PluginStatusRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *PluginStatusRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

type PluginStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Plugin        *PluginInfo            `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStatusResponse) Reset() {
	*x = PluginStatusResponse{}
	mi := &file_services_client_container_proto_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatusResponse) ProtoMessage() {}

func (x *PluginStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_client_container_proto_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatusResponse.ProtoReflect.Descriptor instead.
func (*PluginStatusResponse) Descriptor() ([]byte, []int) {
	return file_services_client_container_proto_agent_proto_rawDescGZIP(), []int{24}
}

func (x *PluginStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PluginStatusResponse) GetPlugin() *PluginInfo {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *PluginStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_services_client_container_proto_agent_proto protoreflect.FileDescriptor

const file_services_client_container_proto_agent_proto_rawDesc = "" +
	"\n" +
	"+services/client-container/proto/agent.proto\x12\x05agent\"\xc4\x03\n" +
	"\x15RegisterDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_type\x18\x03 \x01(\tR\x06osType\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tR\tipAddress\x12#\n" +
	"\rdevice_serial\x18\a \x01(\tR\fdeviceSerial\x12#\n" +
	"\ragent_version\x18\b \x01(\tR\fagentVersion\x12\x17\n" +
	"\acsr_pem\x18\t \x01(\tR\x06csrPem\x12S\n" +
	"\rhardware_info\x18\n" +
	" \x03(\v2..agent.RegisterDeviceRequest.HardwareInfoEntryR\fhardwareInfo\x1a?\n" +
	"\x11HardwareInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x16RegisterDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\x05R\bdeviceId\x12+\n" +
	"\x11verification_code\x18\x03 \x01(\tR\x10verificationCode\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"x\n" +
	"\x13VerifyDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\tR\x06csrPem\"\xc5\x01\n" +
	"\x14VerifyDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fcertificate_pem\x18\x02 \x01(\tR\x0ecertificatePem\x12-\n" +
	"\x12certificate_serial\x18\x03 \x01(\tR\x11certificateSerial\x12!\n" +
	"\fcontainer_id\x18\x04 \x01(\tR\vcontainerId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x84\x02\n" +
	"\fHealthReport\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12*\n" +
	"\x06status\x18\x03 \x01(\v2\x12.agent.AgentStatusR\x06status\x128\n" +
	"\rplugin_health\x18\x04 \x03(\v2\x13.agent.PluginHealthR\fpluginHealth\x12.\n" +
	"\ametrics\x18\x05 \x01(\v2\x14.agent.SystemMetricsR\ametrics\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"i\n" +
	"\vAgentStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"last_error\x18\x02 \x01(\tR\tlastError\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"\x8b\x01\n" +
	"\fPluginHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\"\xe7\x01\n" +
	"\rSystemMetrics\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x01R\x0fcpuUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x03R\x10memoryTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x04 \x01(\x03R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\x05 \x01(\x03R\x0ediskTotalBytes\"\x85\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\x1cnext_report_interval_seconds\x18\x03 \x01(\x03R\x19nextReportIntervalSeconds\"@\n" +
	"\rConfigRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\"\xf0\x01\n" +
	"\x0eConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12N\n" +
	"\rconfiguration\x18\x02 \x03(\v2(.agent.ConfigResponse.ConfigurationEntryR\rconfiguration\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x1a@\n" +
	"\x12ConfigurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x13UpdateConfigRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12S\n" +
	"\rconfiguration\x18\x02 \x03(\v2-.agent.UpdateConfigRequest.ConfigurationEntryR\rconfiguration\x1a@\n" +
	"\x12ConfigurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x11PluginListRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12)\n" +
	"\x10include_inactive\x18\x02 \x01(\bR\x0fincludeInactive\"u\n" +
	"\x12PluginListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\aplugins\x18\x02 \x03(\v2\x11.agent.PluginInfoR\aplugins\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xec\x01\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12;\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1f.agent.PluginInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x14InstallPluginRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x86\x01\n" +
	"\x15InstallPluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"V\n" +
	"\x16UninstallPluginRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\"M\n" +
	"\x17UninstallPluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd2\x01\n" +
	"\x15ActivatePluginRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\x12@\n" +
	"\x06config\x18\x03 \x03(\v2(.agent.ActivatePluginRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x16ActivatePluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\x17DeactivatePluginRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\"N\n" +
	"\x18DeactivatePluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"\x13PluginStatusRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\"u\n" +
	"\x14PluginStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x06plugin\x18\x02 \x01(\v2\x11.agent.PluginInfoR\x06plugin\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xbf\x06\n" +
	"\fAgentService\x12M\n" +
	"\x0eRegisterDevice\x12\x1c.agent.RegisterDeviceRequest\x1a\x1d.agent.RegisterDeviceResponse\x12G\n" +
	"\fVerifyDevice\x12\x1a.agent.VerifyDeviceRequest\x1a\x1b.agent.VerifyDeviceResponse\x12:\n" +
	"\fReportHealth\x12\x13.agent.HealthReport\x1a\x15.agent.HealthResponse\x12?\n" +
	"\x10GetConfiguration\x12\x14.agent.ConfigRequest\x1a\x15.agent.ConfigResponse\x12H\n" +
	"\x13UpdateConfiguration\x12\x1a.agent.UpdateConfigRequest\x1a\x15.agent.ConfigResponse\x12B\n" +
	"\vListPlugins\x12\x18.agent.PluginListRequest\x1a\x19.agent.PluginListResponse\x12J\n" +
	"\rInstallPlugin\x12\x1b.agent.InstallPluginRequest\x1a\x1c.agent.InstallPluginResponse\x12P\n" +
	"\x0fUninstallPlugin\x12\x1d.agent.UninstallPluginRequest\x1a\x1e.agent.UninstallPluginResponse\x12M\n" +
	"\x0eActivatePlugin\x12\x1c.agent.ActivatePluginRequest\x1a\x1d.agent.ActivatePluginResponse\x12S\n" +
	"\x10DeactivatePlugin\x12\x1e.agent.DeactivatePluginRequest\x1a\x1f.agent.DeactivatePluginResponse\x12J\n" +
	"\x0fGetPluginStatus\x12\x1a.agent.PluginStatusRequest\x1a\x1b.agent.PluginStatusResponseB)Z'backend/services/client-container/protob\x06proto3"

var (
	file_services_client_container_proto_agent_proto_rawDescOnce sync.Once
	file_services_client_container_proto_agent_proto_rawDescData []byte
)

func file_services_client_container_proto_agent_proto_rawDescGZIP() []byte {
	file_services_client_container_proto_agent_proto_rawDescOnce.Do(func() {
		file_services_client_container_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_client_container_proto_agent_proto_rawDesc), len(file_services_client_container_proto_agent_proto_rawDesc)))
	})
	return file_services_client_container_proto_agent_proto_rawDescData
}

var file_services_client_container_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_services_client_container_proto_agent_proto_goTypes = []any{
	(*RegisterDeviceRequest)(nil),    // 0: agent.RegisterDeviceRequest
	(*RegisterDeviceResponse)(nil),   // 1: agent.RegisterDeviceResponse
	(*VerifyDeviceRequest)(nil),      // 2: agent.VerifyDeviceRequest
	(*VerifyDeviceResponse)(nil),     // 3: agent.VerifyDeviceResponse
	(*HealthReport)(nil),             // 4: agent.HealthReport
	(*AgentStatus)(nil),              // 5: agent.AgentStatus
	(*PluginHealth)(nil),             // 6: agent.PluginHealth
	(*SystemMetrics)(nil),            // 7: agent.SystemMetrics
	(*HealthResponse)(nil),           // 8: agent.HealthResponse
	(*ConfigRequest)(nil),            // 9: agent.ConfigRequest
	(*ConfigResponse)(nil),           // 10: agent.ConfigResponse
	(*UpdateConfigRequest)(nil),      // 11: agent.UpdateConfigRequest
	(*PluginListRequest)(nil),        // 12: agent.PluginListRequest
	(*PluginListResponse)(nil),       // 13: agent.PluginListResponse
	(*PluginInfo)(nil),               // 14: agent.PluginInfo
	(*InstallPluginRequest)(nil),     // 15: agent.InstallPluginRequest
	(*InstallPluginResponse)(nil),    // 16: agent.InstallPluginResponse
	(*UninstallPluginRequest)(nil),   // 17: agent.UninstallPluginRequest
	(*UninstallPluginResponse)(nil),  // 18: agent.UninstallPluginResponse
	(*ActivatePluginRequest)(nil),    // 19: agent.ActivatePluginRequest
	(*ActivatePluginResponse)(nil),   // 20: agent.ActivatePluginResponse
	(*DeactivatePluginRequest)(nil),  // 21: agent.DeactivatePluginRequest
	(*DeactivatePluginResponse)(nil), // 22: agent.DeactivatePluginResponse
	(*PluginStatusRequest)(nil),      // 23: agent.PluginStatusRequest
	(*PluginStatusResponse)(nil),     // 24: agent.PluginStatusResponse
	nil,                              // 25: agent.RegisterDeviceRequest.HardwareInfoEntry
	nil,                              // 26: agent.ConfigResponse.ConfigurationEntry
	nil,                              // 27: agent.UpdateConfigRequest.ConfigurationEntry
	nil,                              // 28: agent.PluginInfo.MetadataEntry
	nil,                              // 29: agent.ActivatePluginRequest.ConfigEntry
}
var file_services_client_container_proto_agent_proto_depIdxs = []int32{
	25, // 0: agent.RegisterDeviceRequest.hardware_info:type_name -> agent.RegisterDeviceRequest.HardwareInfoEntry
	5,  // 1: agent.HealthReport.status:type_name -> agent.AgentStatus
	6,  // 2: agent.HealthReport.plugin_health:type_name -> agent.PluginHealth
	7,  // 3: agent.HealthReport.metrics:type_name -> agent.SystemMetrics
	26, // 4: agent.ConfigResponse.configuration:type_name -> agent.ConfigResponse.ConfigurationEntry
	27, // 5: agent.UpdateConfigRequest.configuration:type_name -> agent.UpdateConfigRequest.ConfigurationEntry
	14, // 6: agent.PluginListResponse.plugins:type_name -> agent.PluginInfo
	28, // 7: agent.PluginInfo.metadata:type_name -> agent.PluginInfo.MetadataEntry
	29, // 8: agent.ActivatePluginRequest.config:type_name -> agent.ActivatePluginRequest.ConfigEntry
	14, // 9: agent.PluginStatusResponse.plugin:type_name -> agent.PluginInfo
	0,  // 10: agent.AgentService.RegisterDevice:input_type -> agent.RegisterDeviceRequest
	2,  // 11: agent.AgentService.VerifyDevice:input_type -> agent.VerifyDeviceRequest
	4,  // 12: agent.AgentService.ReportHealth:input_type -> agent.HealthReport
	9,  // 13: agent.AgentService.GetConfiguration:input_type -> agent.ConfigRequest
	11, // 14: agent.AgentService.UpdateConfiguration:input_type -> agent.UpdateConfigRequest
	12, // 15: agent.AgentService.ListPlugins:input_type -> agent.PluginListRequest
	15, // 16: agent.AgentService.InstallPlugin:input_type -> agent.InstallPluginRequest
	17, // 17: agent.AgentService.UninstallPlugin:input_type -> agent.UninstallPluginRequest
	19, // 18: agent.AgentService.ActivatePlugin:input_type -> agent.ActivatePluginRequest
	21, // 19: agent.AgentService.DeactivatePlugin:input_type -> agent.DeactivatePluginRequest
	23, // 20: agent.AgentService.GetPluginStatus:input_type -> agent.PluginStatusRequest
	1,  // 21: agent.AgentService.RegisterDevice:output_type -> agent.RegisterDeviceResponse
	3,  // 22: agent.AgentService.VerifyDevice:output_type -> agent.VerifyDeviceResponse
	8,  // 23: agent.AgentService.ReportHealth:output_type -> agent.HealthResponse
	10, // 24: agent.AgentService.GetConfiguration:output_type -> agent.ConfigResponse
	10, // 25: agent.AgentService.UpdateConfiguration:output_type -> agent.ConfigResponse
	13, // 26: agent.AgentService.ListPlugins:output_type -> agent.PluginListResponse
	16, // 27: agent.AgentService.InstallPlugin:output_type -> agent.InstallPluginResponse
	18, // 28: agent.AgentService.UninstallPlugin:output_type -> agent.UninstallPluginResponse
	20, // 29: agent.AgentService.ActivatePlugin:output_type -> agent.ActivatePluginResponse
	22, // 30: agent.AgentService.DeactivatePlugin:output_type -> agent.DeactivatePluginResponse
	24, // 31: agent.AgentService.GetPluginStatus:output_type -> agent.PluginStatusResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_services_client_container_proto_agent_proto_init() }
func file_services_client_container_proto_agent_proto_init() {
	if File_services_client_container_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_client_container_proto_agent_proto_rawDesc), len(file_services_client_container_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_client_container_proto_agent_proto_goTypes,
		DependencyIndexes: file_services_client_container_proto_agent_proto_depIdxs,
		MessageInfos:      file_services_client_container_proto_agent_proto_msgTypes,
	}.Build()
	File_services_client_container_proto_agent_proto = out.File
	file_services_client_container_proto_agent_proto_goTypes = nil
	file_services_client_container_proto_agent_proto_depIdxs = nil
}
