// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: services/navigation/proto/navigation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NavigationService_GetMenu_FullMethodName        = "/navigation.NavigationService/GetMenu"
	NavigationService_ListMenus_FullMethodName      = "/navigation.NavigationService/ListMenus"
	NavigationService_CreateMenu_FullMethodName     = "/navigation.NavigationService/CreateMenu"
	NavigationService_UpdateMenu_FullMethodName     = "/navigation.NavigationService/UpdateMenu"
	NavigationService_DeleteMenu_FullMethodName     = "/navigation.NavigationService/DeleteMenu"
	NavigationService_ListMenuRoles_FullMethodName  = "/navigation.NavigationService/ListMenuRoles"
	NavigationService_AddMenuRole_FullMethodName    = "/navigation.NavigationService/AddMenuRole"
	NavigationService_RemoveMenuRole_FullMethodName = "/navigation.NavigationService/RemoveMenuRole"
)

// NavigationServiceClient is the client API for NavigationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Navigation Service gRPC API
type NavigationServiceClient interface {
	// Menu operations
	GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*MenuResponse, error)
	ListMenus(ctx context.Context, in *ListMenusRequest, opts ...grpc.CallOption) (*ListMenusResponse, error)
	CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*MenuResponse, error)
	UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*MenuResponse, error)
	DeleteMenu(ctx context.Context, in *DeleteMenuRequest, opts ...grpc.CallOption) (*DeleteMenuResponse, error)
	// Menu Role operations
	ListMenuRoles(ctx context.Context, in *ListMenuRolesRequest, opts ...grpc.CallOption) (*ListMenuRolesResponse, error)
	AddMenuRole(ctx context.Context, in *AddMenuRoleRequest, opts ...grpc.CallOption) (*AddMenuRoleResponse, error)
	RemoveMenuRole(ctx context.Context, in *RemoveMenuRoleRequest, opts ...grpc.CallOption) (*RemoveMenuRoleResponse, error)
}

type navigationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNavigationServiceClient(cc grpc.ClientConnInterface) NavigationServiceClient {
	return &navigationServiceClient{cc}
}

func (c *navigationServiceClient) GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*MenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuResponse)
	err := c.cc.Invoke(ctx, NavigationService_GetMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navigationServiceClient) ListMenus(ctx context.Context, in *ListMenusRequest, opts ...grpc.CallOption) (*ListMenusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMenusResponse)
	err := c.cc.Invoke(ctx, NavigationService_ListMenus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navigationServiceClient) CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*MenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuResponse)
	err := c.cc.Invoke(ctx, NavigationService_CreateMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navigationServiceClient) UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*MenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuResponse)
	err := c.cc.Invoke(ctx, NavigationService_UpdateMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navigationServiceClient) DeleteMenu(ctx context.Context, in *DeleteMenuRequest, opts ...grpc.CallOption) (*DeleteMenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMenuResponse)
	err := c.cc.Invoke(ctx, NavigationService_DeleteMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navigationServiceClient) ListMenuRoles(ctx context.Context, in *ListMenuRolesRequest, opts ...grpc.CallOption) (*ListMenuRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMenuRolesResponse)
	err := c.cc.Invoke(ctx, NavigationService_ListMenuRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navigationServiceClient) AddMenuRole(ctx context.Context, in *AddMenuRoleRequest, opts ...grpc.CallOption) (*AddMenuRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMenuRoleResponse)
	err := c.cc.Invoke(ctx, NavigationService_AddMenuRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *navigationServiceClient) RemoveMenuRole(ctx context.Context, in *RemoveMenuRoleRequest, opts ...grpc.CallOption) (*RemoveMenuRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMenuRoleResponse)
	err := c.cc.Invoke(ctx, NavigationService_RemoveMenuRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NavigationServiceServer is the server API for NavigationService service.
// All implementations must embed UnimplementedNavigationServiceServer
// for forward compatibility.
//
// Navigation Service gRPC API
type NavigationServiceServer interface {
	// Menu operations
	GetMenu(context.Context, *GetMenuRequest) (*MenuResponse, error)
	ListMenus(context.Context, *ListMenusRequest) (*ListMenusResponse, error)
	CreateMenu(context.Context, *CreateMenuRequest) (*MenuResponse, error)
	UpdateMenu(context.Context, *UpdateMenuRequest) (*MenuResponse, error)
	DeleteMenu(context.Context, *DeleteMenuRequest) (*DeleteMenuResponse, error)
	// Menu Role operations
	ListMenuRoles(context.Context, *ListMenuRolesRequest) (*ListMenuRolesResponse, error)
	AddMenuRole(context.Context, *AddMenuRoleRequest) (*AddMenuRoleResponse, error)
	RemoveMenuRole(context.Context, *RemoveMenuRoleRequest) (*RemoveMenuRoleResponse, error)
	mustEmbedUnimplementedNavigationServiceServer()
}

// UnimplementedNavigationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNavigationServiceServer struct{}

func (UnimplementedNavigationServiceServer) GetMenu(context.Context, *GetMenuRequest) (*MenuResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenu not implemented")
}
func (UnimplementedNavigationServiceServer) ListMenus(context.Context, *ListMenusRequest) (*ListMenusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMenus not implemented")
}
func (UnimplementedNavigationServiceServer) CreateMenu(context.Context, *CreateMenuRequest) (*MenuResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMenu not implemented")
}
func (UnimplementedNavigationServiceServer) UpdateMenu(context.Context, *UpdateMenuRequest) (*MenuResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMenu not implemented")
}
func (UnimplementedNavigationServiceServer) DeleteMenu(context.Context, *DeleteMenuRequest) (*DeleteMenuResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMenu not implemented")
}
func (UnimplementedNavigationServiceServer) ListMenuRoles(context.Context, *ListMenuRolesRequest) (*ListMenuRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMenuRoles not implemented")
}
func (UnimplementedNavigationServiceServer) AddMenuRole(context.Context, *AddMenuRoleRequest) (*AddMenuRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMenuRole not implemented")
}
func (UnimplementedNavigationServiceServer) RemoveMenuRole(context.Context, *RemoveMenuRoleRequest) (*RemoveMenuRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMenuRole not implemented")
}
func (UnimplementedNavigationServiceServer) mustEmbedUnimplementedNavigationServiceServer() {}
func (UnimplementedNavigationServiceServer) testEmbeddedByValue()                           {}

// UnsafeNavigationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NavigationServiceServer will
// result in compilation errors.
type UnsafeNavigationServiceServer interface {
	mustEmbedUnimplementedNavigationServiceServer()
}

func RegisterNavigationServiceServer(s grpc.ServiceRegistrar, srv NavigationServiceServer) {
	// If the following call panics, it indicates UnimplementedNavigationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NavigationService_ServiceDesc, srv)
}

func _NavigationService_GetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavigationServiceServer).GetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavigationService_GetMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavigationServiceServer).GetMenu(ctx, req.(*GetMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NavigationService_ListMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMenusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavigationServiceServer).ListMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavigationService_ListMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavigationServiceServer).ListMenus(ctx, req.(*ListMenusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NavigationService_CreateMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavigationServiceServer).CreateMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavigationService_CreateMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavigationServiceServer).CreateMenu(ctx, req.(*CreateMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NavigationService_UpdateMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavigationServiceServer).UpdateMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavigationService_UpdateMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavigationServiceServer).UpdateMenu(ctx, req.(*UpdateMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NavigationService_DeleteMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavigationServiceServer).DeleteMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavigationService_DeleteMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavigationServiceServer).DeleteMenu(ctx, req.(*DeleteMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NavigationService_ListMenuRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMenuRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavigationServiceServer).ListMenuRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavigationService_ListMenuRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavigationServiceServer).ListMenuRoles(ctx, req.(*ListMenuRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NavigationService_AddMenuRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMenuRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavigationServiceServer).AddMenuRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavigationService_AddMenuRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavigationServiceServer).AddMenuRole(ctx, req.(*AddMenuRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NavigationService_RemoveMenuRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMenuRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NavigationServiceServer).RemoveMenuRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NavigationService_RemoveMenuRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NavigationServiceServer).RemoveMenuRole(ctx, req.(*RemoveMenuRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NavigationService_ServiceDesc is the grpc.ServiceDesc for NavigationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NavigationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "navigation.NavigationService",
	HandlerType: (*NavigationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMenu",
			Handler:    _NavigationService_GetMenu_Handler,
		},
		{
			MethodName: "ListMenus",
			Handler:    _NavigationService_ListMenus_Handler,
		},
		{
			MethodName: "CreateMenu",
			Handler:    _NavigationService_CreateMenu_Handler,
		},
		{
			MethodName: "UpdateMenu",
			Handler:    _NavigationService_UpdateMenu_Handler,
		},
		{
			MethodName: "DeleteMenu",
			Handler:    _NavigationService_DeleteMenu_Handler,
		},
		{
			MethodName: "ListMenuRoles",
			Handler:    _NavigationService_ListMenuRoles_Handler,
		},
		{
			MethodName: "AddMenuRole",
			Handler:    _NavigationService_AddMenuRole_Handler,
		},
		{
			MethodName: "RemoveMenuRole",
			Handler:    _NavigationService_RemoveMenuRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/navigation/proto/navigation.proto",
}
