// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: services/navigation/proto/navigation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Menu messages
type GetMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{0}
}

func (x *GetMenuRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListMenusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenusRequest) Reset() {
	*x = ListMenusRequest{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenusRequest) ProtoMessage() {}

func (x *ListMenusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenusRequest.ProtoReflect.Descriptor instead.
func (*ListMenusRequest) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{1}
}

type CreateMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuRequest) Reset() {
	*x = CreateMenuRequest{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuRequest) ProtoMessage() {}

func (x *CreateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuRequest) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMenuRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMenuRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMenuRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type UpdateMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Updates       map[string]string      `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuRequest) Reset() {
	*x = UpdateMenuRequest{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuRequest) ProtoMessage() {}

func (x *UpdateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuRequest) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMenuRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMenuRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

type DeleteMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuRequest) Reset() {
	*x = DeleteMenuRequest{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuRequest) ProtoMessage() {}

func (x *DeleteMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuRequest.ProtoReflect.Descriptor instead.
func (*DeleteMenuRequest) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMenuRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Uri           string                 `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{5}
}

func (x *Menu) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Menu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Menu) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Menu) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type MenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menu          *Menu                  `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuResponse) Reset() {
	*x = MenuResponse{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuResponse) ProtoMessage() {}

func (x *MenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuResponse.ProtoReflect.Descriptor instead.
func (*MenuResponse) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{6}
}

func (x *MenuResponse) GetMenu() *Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

type ListMenusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menus         []*Menu                `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenusResponse) Reset() {
	*x = ListMenusResponse{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenusResponse) ProtoMessage() {}

func (x *ListMenusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenusResponse.ProtoReflect.Descriptor instead.
func (*ListMenusResponse) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{7}
}

func (x *ListMenusResponse) GetMenus() []*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

type DeleteMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuResponse) Reset() {
	*x = DeleteMenuResponse{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuResponse) ProtoMessage() {}

func (x *DeleteMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuResponse.ProtoReflect.Descriptor instead.
func (*DeleteMenuResponse) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMenuResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Menu Role messages
type ListMenuRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuId        int32                  `protobuf:"varint,1,opt,name=menu_id,json=menuId,proto3" json:"menu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuRolesRequest) Reset() {
	*x = ListMenuRolesRequest{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuRolesRequest) ProtoMessage() {}

func (x *ListMenuRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuRolesRequest.ProtoReflect.Descriptor instead.
func (*ListMenuRolesRequest) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{9}
}

func (x *ListMenuRolesRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

type AddMenuRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuId        int32                  `protobuf:"varint,1,opt,name=menu_id,json=menuId,proto3" json:"menu_id,omitempty"`
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMenuRoleRequest) Reset() {
	*x = AddMenuRoleRequest{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMenuRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMenuRoleRequest) ProtoMessage() {}

func (x *AddMenuRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMenuRoleRequest.ProtoReflect.Descriptor instead.
func (*AddMenuRoleRequest) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{10}
}

func (x *AddMenuRoleRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *AddMenuRoleRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RemoveMenuRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuId        int32                  `protobuf:"varint,1,opt,name=menu_id,json=menuId,proto3" json:"menu_id,omitempty"`
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMenuRoleRequest) Reset() {
	*x = RemoveMenuRoleRequest{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMenuRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMenuRoleRequest) ProtoMessage() {}

func (x *RemoveMenuRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMenuRoleRequest.ProtoReflect.Descriptor instead.
func (*RemoveMenuRoleRequest) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveMenuRoleRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *RemoveMenuRoleRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type MenuRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuId        int32                  `protobuf:"varint,1,opt,name=menu_id,json=menuId,proto3" json:"menu_id,omitempty"`
	RoleId        int32                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuRole) Reset() {
	*x = MenuRole{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRole) ProtoMessage() {}

func (x *MenuRole) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRole.ProtoReflect.Descriptor instead.
func (*MenuRole) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{12}
}

func (x *MenuRole) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *MenuRole) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type ListMenuRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuRoles     []*MenuRole            `protobuf:"bytes,1,rep,name=menu_roles,json=menuRoles,proto3" json:"menu_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuRolesResponse) Reset() {
	*x = ListMenuRolesResponse{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuRolesResponse) ProtoMessage() {}

func (x *ListMenuRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuRolesResponse.ProtoReflect.Descriptor instead.
func (*ListMenuRolesResponse) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{13}
}

func (x *ListMenuRolesResponse) GetMenuRoles() []*MenuRole {
	if x != nil {
		return x.MenuRoles
	}
	return nil
}

type AddMenuRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuRole      *MenuRole              `protobuf:"bytes,1,opt,name=menu_role,json=menuRole,proto3" json:"menu_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMenuRoleResponse) Reset() {
	*x = AddMenuRoleResponse{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMenuRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMenuRoleResponse) ProtoMessage() {}

func (x *AddMenuRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMenuRoleResponse.ProtoReflect.Descriptor instead.
func (*AddMenuRoleResponse) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{14}
}

func (x *AddMenuRoleResponse) GetMenuRole() *MenuRole {
	if x != nil {
		return x.MenuRole
	}
	return nil
}

type RemoveMenuRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMenuRoleResponse) Reset() {
	*x = RemoveMenuRoleResponse{}
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMenuRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMenuRoleResponse) ProtoMessage() {}

func (x *RemoveMenuRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_navigation_proto_navigation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMenuRoleResponse.ProtoReflect.Descriptor instead.
func (*RemoveMenuRoleResponse) Descriptor() ([]byte, []int) {
	return file_services_navigation_proto_navigation_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveMenuRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_services_navigation_proto_navigation_proto protoreflect.FileDescriptor

const file_services_navigation_proto_navigation_proto_rawDesc = "" +
	"\n" +
	"*services/navigation/proto/navigation.proto\x12\n" +
	"navigation\" \n" +
	"\x0eGetMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x12\n" +
	"\x10ListMenusRequest\"O\n" +
	"\x11CreateMenuRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\"\xa5\x01\n" +
	"\x11UpdateMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12D\n" +
	"\aupdates\x18\x02 \x03(\v2*.navigation.UpdateMenuRequest.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\x11DeleteMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"R\n" +
	"\x04Menu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x10\n" +
	"\x03uri\x18\x04 \x01(\tR\x03uri\"4\n" +
	"\fMenuResponse\x12$\n" +
	"\x04menu\x18\x01 \x01(\v2\x10.navigation.MenuR\x04menu\";\n" +
	"\x11ListMenusResponse\x12&\n" +
	"\x05menus\x18\x01 \x03(\v2\x10.navigation.MenuR\x05menus\".\n" +
	"\x12DeleteMenuResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x14ListMenuRolesRequest\x12\x17\n" +
	"\amenu_id\x18\x01 \x01(\x05R\x06menuId\"F\n" +
	"\x12AddMenuRoleRequest\x12\x17\n" +
	"\amenu_id\x18\x01 \x01(\x05R\x06menuId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\"I\n" +
	"\x15RemoveMenuRoleRequest\x12\x17\n" +
	"\amenu_id\x18\x01 \x01(\x05R\x06menuId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\"<\n" +
	"\bMenuRole\x12\x17\n" +
	"\amenu_id\x18\x01 \x01(\x05R\x06menuId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x05R\x06roleId\"L\n" +
	"\x15ListMenuRolesResponse\x123\n" +
	"\n" +
	"menu_roles\x18\x01 \x03(\v2\x14.navigation.MenuRoleR\tmenuRoles\"H\n" +
	"\x13AddMenuRoleResponse\x121\n" +
	"\tmenu_role\x18\x01 \x01(\v2\x14.navigation.MenuRoleR\bmenuRole\"2\n" +
	"\x16RemoveMenuRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf8\x04\n" +
	"\x11NavigationService\x12?\n" +
	"\aGetMenu\x12\x1a.navigation.GetMenuRequest\x1a\x18.navigation.MenuResponse\x12H\n" +
	"\tListMenus\x12\x1c.navigation.ListMenusRequest\x1a\x1d.navigation.ListMenusResponse\x12E\n" +
	"\n" +
	"CreateMenu\x12\x1d.navigation.CreateMenuRequest\x1a\x18.navigation.MenuResponse\x12E\n" +
	"\n" +
	"UpdateMenu\x12\x1d.navigation.UpdateMenuRequest\x1a\x18.navigation.MenuResponse\x12K\n" +
	"\n" +
	"DeleteMenu\x12\x1d.navigation.DeleteMenuRequest\x1a\x1e.navigation.DeleteMenuResponse\x12T\n" +
	"\rListMenuRoles\x12 .navigation.ListMenuRolesRequest\x1a!.navigation.ListMenuRolesResponse\x12N\n" +
	"\vAddMenuRole\x12\x1e.navigation.AddMenuRoleRequest\x1a\x1f.navigation.AddMenuRoleResponse\x12W\n" +
	"\x0eRemoveMenuRole\x12!.navigation.RemoveMenuRoleRequest\x1a\".navigation.RemoveMenuRoleResponseB#Z!backend/services/navigation/protob\x06proto3"

var (
	file_services_navigation_proto_navigation_proto_rawDescOnce sync.Once
	file_services_navigation_proto_navigation_proto_rawDescData []byte
)

func file_services_navigation_proto_navigation_proto_rawDescGZIP() []byte {
	file_services_navigation_proto_navigation_proto_rawDescOnce.Do(func() {
		file_services_navigation_proto_navigation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_navigation_proto_navigation_proto_rawDesc), len(file_services_navigation_proto_navigation_proto_rawDesc)))
	})
	return file_services_navigation_proto_navigation_proto_rawDescData
}

var file_services_navigation_proto_navigation_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_services_navigation_proto_navigation_proto_goTypes = []any{
	(*GetMenuRequest)(nil),         // 0: navigation.GetMenuRequest
	(*ListMenusRequest)(nil),       // 1: navigation.ListMenusRequest
	(*CreateMenuRequest)(nil),      // 2: navigation.CreateMenuRequest
	(*UpdateMenuRequest)(nil),      // 3: navigation.UpdateMenuRequest
	(*DeleteMenuRequest)(nil),      // 4: navigation.DeleteMenuRequest
	(*Menu)(nil),                   // 5: navigation.Menu
	(*MenuResponse)(nil),           // 6: navigation.MenuResponse
	(*ListMenusResponse)(nil),      // 7: navigation.ListMenusResponse
	(*DeleteMenuResponse)(nil),     // 8: navigation.DeleteMenuResponse
	(*ListMenuRolesRequest)(nil),   // 9: navigation.ListMenuRolesRequest
	(*AddMenuRoleRequest)(nil),     // 10: navigation.AddMenuRoleRequest
	(*RemoveMenuRoleRequest)(nil),  // 11: navigation.RemoveMenuRoleRequest
	(*MenuRole)(nil),               // 12: navigation.MenuRole
	(*ListMenuRolesResponse)(nil),  // 13: navigation.ListMenuRolesResponse
	(*AddMenuRoleResponse)(nil),    // 14: navigation.AddMenuRoleResponse
	(*RemoveMenuRoleResponse)(nil), // 15: navigation.RemoveMenuRoleResponse
	nil,                            // 16: navigation.UpdateMenuRequest.UpdatesEntry
}
var file_services_navigation_proto_navigation_proto_depIdxs = []int32{
	16, // 0: navigation.UpdateMenuRequest.updates:type_name -> navigation.UpdateMenuRequest.UpdatesEntry
	5,  // 1: navigation.MenuResponse.menu:type_name -> navigation.Menu
	5,  // 2: navigation.ListMenusResponse.menus:type_name -> navigation.Menu
	12, // 3: navigation.ListMenuRolesResponse.menu_roles:type_name -> navigation.MenuRole
	12, // 4: navigation.AddMenuRoleResponse.menu_role:type_name -> navigation.MenuRole
	0,  // 5: navigation.NavigationService.GetMenu:input_type -> navigation.GetMenuRequest
	1,  // 6: navigation.NavigationService.ListMenus:input_type -> navigation.ListMenusRequest
	2,  // 7: navigation.NavigationService.CreateMenu:input_type -> navigation.CreateMenuRequest
	3,  // 8: navigation.NavigationService.UpdateMenu:input_type -> navigation.UpdateMenuRequest
	4,  // 9: navigation.NavigationService.DeleteMenu:input_type -> navigation.DeleteMenuRequest
	9,  // 10: navigation.NavigationService.ListMenuRoles:input_type -> navigation.ListMenuRolesRequest
	10, // 11: navigation.NavigationService.AddMenuRole:input_type -> navigation.AddMenuRoleRequest
	11, // 12: navigation.NavigationService.RemoveMenuRole:input_type -> navigation.RemoveMenuRoleRequest
	6,  // 13: navigation.NavigationService.GetMenu:output_type -> navigation.MenuResponse
	7,  // 14: navigation.NavigationService.ListMenus:output_type -> navigation.ListMenusResponse
	6,  // 15: navigation.NavigationService.CreateMenu:output_type -> navigation.MenuResponse
	6,  // 16: navigation.NavigationService.UpdateMenu:output_type -> navigation.MenuResponse
	8,  // 17: navigation.NavigationService.DeleteMenu:output_type -> navigation.DeleteMenuResponse
	13, // 18: navigation.NavigationService.ListMenuRoles:output_type -> navigation.ListMenuRolesResponse
	14, // 19: navigation.NavigationService.AddMenuRole:output_type -> navigation.AddMenuRoleResponse
	15, // 20: navigation.NavigationService.RemoveMenuRole:output_type -> navigation.RemoveMenuRoleResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_services_navigation_proto_navigation_proto_init() }
func file_services_navigation_proto_navigation_proto_init() {
	if File_services_navigation_proto_navigation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_navigation_proto_navigation_proto_rawDesc), len(file_services_navigation_proto_navigation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_navigation_proto_navigation_proto_goTypes,
		DependencyIndexes: file_services_navigation_proto_navigation_proto_depIdxs,
		MessageInfos:      file_services_navigation_proto_navigation_proto_msgTypes,
	}.Build()
	File_services_navigation_proto_navigation_proto = out.File
	file_services_navigation_proto_navigation_proto_goTypes = nil
	file_services_navigation_proto_navigation_proto_depIdxs = nil
}
